const state={documents:[],accounts:0,issues:0,readiness:0,rounds:0,report:'draft'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('kosif-one-rebuild',JSON.stringify(state))}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('kosif-one-rebuild')||'{}'))}catch{};render()}
function render(){
  $('#metricDocs').textContent=state.documents.length.toLocaleString('ar-SA');$('#metricDocsNote').textContent=state.documents.length?'تم استلام مصادر':'بانتظار الرفع';
  $('#metricAccounts').textContent=state.accounts.toLocaleString('ar-SA');$('#metricAccountsNote').textContent=state.accounts?'حساب قابل للفحص':'لم يُحمّل ميزان';
  $('#metricIssues').textContent=state.issues.toLocaleString('ar-SA');$('#metricReadiness').textContent=state.readiness+'%';$('#metricReadinessNote').textContent=state.readiness?'تقدم مسار المراجعة':'أكمل بوابات الملف';
  $('#balanceValue').textContent=state.accounts?'متزن حسابيًا':'بانتظار البيانات';$('#balanceNote').textContent=state.accounts?'تم فحص الأرصدة الأولية.':'حمّل نموذج 5,000 حساب أو ارفع ملفك.';
  $('#riskValue').textContent=state.issues?'إشارة تحتاج مراجعة':'لا توجد إشارات';$('#riskNote').textContent=state.issues?'افتح جولة المجلس لتوثيق القرار.':'ستظهر بعد تشغيل الفحص.';$('#sourceValue').textContent=state.documents[0]?.name||'—';
  $('#roundStatus .round-number').textContent=String(state.rounds).padStart(2,'0');$('#roundStatus strong').textContent=state.rounds?'الجولة '+state.rounds+' مفتوحة':'لم تبدأ جولة بعد';$('#roundStatus p').textContent=state.rounds?'ملاحظات المجلس جاهزة للإجابة.':'عقد الجولة يفتح مسار الملاحظات والطلبات.';
  $('#evidenceCount').textContent=(state.documents.length+2)+' طلبات';
  const list=$('#documentList');list.innerHTML=state.documents.length?state.documents.map((d,i)=>`<div class="document-row"><div><strong>${esc(d.name)}</strong><small>مصدر ${i+1} · جاهز للفحص</small></div><span class="file-type">${esc(d.type)}</span></div>`).join(''):'<div class="empty-state">لم تُضف مستندات بعد. ابدأ بكشف البنك أو ميزان المراجعة.</div>';
  const rounds=$('#roundList');rounds.innerHTML=state.rounds?[...Array(state.rounds)].map((_,i)=>`<div class="round-item"><b>جولة ${String(i+1).padStart(2,'0')}</b><br><span>تم تسجيلها وتحتاج مراجعة الملاحظات.</span></div>`).join(''):'<div class="empty-state">ستظهر هنا ملاحظات المجلس.</div>';
  $('#reportPaper').querySelector('.paper-top span').textContent=state.report==='ready'?'مسودة جاهزة للمراجعة':'مسودة غير معتمدة';
}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function loadDemo(){state.accounts=5000;state.issues=3;state.readiness=Math.max(state.readiness,32);state.documents=[{name:'ميزان_المراجعة_5000_حساب.csv',type:'CSV'},{name:'دليل_إجراءات_المراجعة.pdf',type:'PDF'}];save();render();document.querySelector('#analysisSection').scrollIntoView({behavior:'smooth'});}
function handleFiles(files){for(const file of files){if(!state.documents.some(d=>d.name===file.name))state.documents.push({name:file.name,type:(file.name.split('.').pop()||'FILE').toUpperCase()})}state.readiness=Math.min(100,Math.max(state.readiness,18));save();render()}
function go(step){$$('.rail-step').forEach(b=>b.classList.toggle('active',b.dataset.step===step));const target=$('#'+({intake:'intakeSection',analysis:'analysisSection',council:'councilSection',evidence:'reportSection',report:'reportSection'}[step]));target?.scrollIntoView({behavior:'smooth',block:'start'})}
function runAnalysis(){if(!state.accounts&&!state.documents.length){state.issues=1;$('#riskNote').textContent='أضف مصدرًا قبل تشغيل الفحص.'}else{state.readiness=Math.max(state.readiness,56);state.issues=state.documents.length?2:state.issues;$('#riskNote').textContent='تم تحديد نقاط تحتاج جولة المجلس.'}save();render()}
function runCouncil(){state.rounds+=1;state.readiness=Math.max(state.readiness,72);save();render();go('council')}
function buildReport(){state.report='ready';state.readiness=Math.max(state.readiness,88);save();render();go('report')}
function initVoice(){const panel=$('#voicePanel'),fab=$('#voiceFab'),start=$('#voiceStart'),close=$('#voiceClose'),transcript=$('#voiceTranscript');fab.onclick=()=>{panel.hidden=!panel.hidden};close.onclick=()=>{panel.hidden=true};start.onclick=()=>{if(!('speechSynthesis' in window)){transcript.insertAdjacentHTML('beforeend','<div class="voice-hint">الصوت غير متاح في هذا المتصفح.</div>');return}const text='جاهزية الملف '+state.readiness+' بالمئة. '+(state.accounts?'الميزان محمّل ويمكنك عقد جولة المجلس.':'ابدأ برفع المستندات أو حمّل الملف التجريبي.');transcript.insertAdjacentHTML('beforeend',`<div class="voice-hint">${text}</div>`);window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(text))}}
$('#heroUpload').onclick=()=>{$('#fileInput').click();go('intake')};$('#heroDemo').onclick=loadDemo;$('#sideCouncil').onclick=runCouncil;$('#analyzeButton').onclick=runAnalysis;$('#councilButton').onclick=runCouncil;$('#reportButton').onclick=buildReport;$('#fileInput').onchange=e=>handleFiles([...e.target.files]);$('#uploadZone').ondragover=e=>{e.preventDefault()};$('#uploadZone').ondrop=e=>{e.preventDefault();handleFiles([...e.dataTransfer.files])};$('#resetButton').onclick=()=>{localStorage.removeItem('kosif-one-rebuild');location.reload()};$$('.rail-step').forEach(b=>b.onclick=()=>go(b.dataset.step));initVoice();load();
