import{generateDemoAccounts,validateTrialBalance,calculateMateriality,detectRisks,parseCsv,formatMoneyMinor}from'./engine.js';
import{convene,councilVerdictLabel,stanceLabel}from'./council.js';
import{createEngagement,deriveEngagementStage,nextActionForEngagement,reportReadiness}from'./v5/engagement-machine.js';
import{evidenceRequestMetrics}from'./v5/evidence-requests.js';
import{proposeAdjustment,decideAdjustment,buildAdjustedTrialBalance}from'./v5/adjustment-ledger.js';
import{buildReportPlan}from'./v5/report-recipes.js';
import{buildEngagementTraceability,traceabilityMetrics,traceAncestors}from'./v5/traceability.js';
import{recordCouncilRound,ingestEvidenceBatch}from'./v5/review-loop.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let engagement=createEngagement({id:'ENG-V5-DEMO',entity:'ارتباط KOSIF V5',period:'2026-12-31',jurisdiction:'SA',framework:'IFRS',engagementType:'audit',currency:'SAR'}),analysis=null,materiality=null,risks=[],selectedRecipePlan=buildReportPlan('ميزانية'),activeRequestId=null;
const money=v=>formatMoneyMinor(v??0n,engagement.currency??'SAR');
function classifyDocument(file){const name=file.name.toLowerCase(),ext=name.split('.').pop();if(/trial|balance|ميزان/.test(name)||ext==='csv')return'trial-balance';if(/chart|coa|دليل.*حساب/.test(name))return'chart-of-accounts';if(/ledger|استاذ|أستاذ/.test(name))return'general-ledger';if(/journal|قيد|قيود/.test(name))return'journal';if(/bank|بنك/.test(name))return'bank-statement';if(/financial|statement|قوائم|ميزاني/.test(name))return'financial-statements';if(ext==='pdf')return'pdf-document';if(['xlsx','xls'].includes(ext))return'spreadsheet';if(['doc','docx'].includes(ext))return'word-document';if(['png','jpg','jpeg','webp','heic'].includes(ext))return'image-document';return ext?`${ext}-document`:'unknown'}
async function sha256(file){const bytes=await file.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
const nextDocumentId=()=>`DOC-${String(engagement.documents.length+1).padStart(4,'0')}`;
const issueFromRisk=(risk,index)=>({id:`ISS-${String(index+1).padStart(4,'0')}`,title:risk.title,severity:risk.severity,status:'open',riskIds:[risk.id],evidenceIds:[],accountId:risk.accountId,amountMinor:risk.amount?.toString?.()??'0'});
async function registerFile(file){const id=nextDocumentId(),type=classifyDocument(file),hash=await sha256(file);engagement.documents.push({id,name:file.name,type,mime:file.type||'application/octet-stream',size:file.size,sha256:hash,version:1,status:'classified',createdAt:new Date().toISOString()});if(type==='trial-balance'&&file.name.toLowerCase().endsWith('.csv')){try{loadTrialBalance(parseCsv(await file.text()),file.name)}catch(error){console.warn('CSV analysis failed',error)}}engagement.stage=deriveEngagementStage(engagement)}
function loadTrialBalance(rows,sourceName){analysis=validateTrialBalance(rows);const benchmarkAmount=analysis.rows.reduce((sum,row)=>sum+(row.debit>row.credit?row.debit:row.credit),0n)/2n;materiality=calculateMateriality({benchmark:'assets',amountMinor:benchmarkAmount,risk:'medium'});risks=detectRisks(analysis.rows,materiality.overall);engagement.entity=sourceName==='KOSIF Demo 5000'?'شركة محمود الدسوقي — نموذج 5000 حساب':engagement.entity;engagement.issues=risks.slice(0,12).map(issueFromRisk);engagement.stage=deriveEngagementStage(engagement)}
function loadDemo(){engagement=createEngagement({id:'ENG-V5-DEMO',entity:'شركة محمود الدسوقي — نموذج 5000 حساب',period:'2026-12-31',jurisdiction:'SA',framework:'IFRS',engagementType:'audit',currency:'SAR'});engagement.documents.push({id:'DOC-0001',name:'KOSIF_Demo_Trial_Balance_5000.csv',type:'trial-balance',mime:'text/csv',size:0,sha256:'demo-deterministic-seed-380019',version:1,status:'classified',createdAt:new Date().toISOString()});loadTrialBalance(generateDemoAccounts(5000,380019),'KOSIF Demo 5000');render()}
const currentCategories=()=>analysis?[...new Set(analysis.rows.map(r=>r.category))]:[],currentDocumentTypes=()=>[...new Set(engagement.documents.map(d=>d.type))];
function renderNow(){const next=nextActionForEngagement(engagement);$('#stageBadge').textContent=next.stage;$('#nextAction').textContent=next.label;$('#readinessValue').textContent=`${next.readiness.score}%`;document.querySelectorAll('.journey [data-stage]').forEach(n=>n.classList.toggle('active',n.dataset.stage===next.stage))}
function renderDocuments(){const target=$('#documentList');if(!engagement.documents.length){target.className='stack empty';target.textContent='لا توجد مستندات بعد.';return}target.className='stack';target.innerHTML=engagement.documents.map(doc=>`<article class="doc"><header><strong>${esc(doc.id)} · ${esc(doc.name)}</strong><span class="badge">${esc(doc.type)}</span></header><small>${Number(doc.size||0).toLocaleString('ar-SA')} بايت · v${doc.version}</small><div class="hash">SHA-256: ${esc(doc.sha256)}</div></article>`).join('')}
function renderRecipe(){selectedRecipePlan=buildReportPlan(selectedRecipePlan?.recipe?.id??$('#recipeInput').value,{categories:currentCategories(),documentTypes:currentDocumentTypes()});const target=$('#recipeResult');if(!selectedRecipePlan.understood){target.innerHTML='<div class="callout">لم أتعرف على التقرير. جرّب: ميزانية، قوائم مالية، تقرير مراجعة، خطاب الإدارة، مراجعة مخزون.</div>';return}target.innerHTML=`<div class="callout"><strong>${esc(selectedRecipePlan.recipe.title)}</strong><br><small>نوع الارتباط: ${esc(selectedRecipePlan.recipe.engagementType)} · ${selectedRecipePlan.required.length} متطلبات ما زالت مطلوبة</small></div>${selectedRecipePlan.requirements.map(item=>`<div class="requirement"><div><strong>${esc(item.title)}</strong><small>${esc(item.reason||'')}</small></div><span class="status-${item.status}">${item.status==='satisfied'?'موجود':'مطلوب'}</span></div>`).join('')}`}
function councilInput(){return{analysis,materiality,risks,findings:engagement.issues.map(i=>({id:i.id,title:i.title,severity:i.severity,status:i.status,amountMinor:i.amountMinor??'0'})),workpapers:[],pbc:engagement.requests.map(r=>({id:r.id,title:r.title,status:r.status,riskIds:r.riskIds??[]})),evidence:engagement.evidence.map(i=>({id:i.id,title:i.title,status:i.reviewStatus==='reviewed'?'reviewed':'received',sourceType:i.sourceType,obtainedDirectly:i.sourceType==='external',fileHash:i.sha256??'',documentDate:i.documentDate??new Date().toISOString().slice(0,10),riskIds:i.riskIds??[]})),journalReview:null,analytics:null,opinion:null,gates:[],graph:null,currency:engagement.currency}}
function runCouncil(){if(!analysis){const positions=[{seatId:'engagement',title:'مدير الارتباط',domain:'تحديد نطاق العمل',stance:'caution',statement:'المستندات مسجلة، لكن لا توجد بعد بيانات مالية منظمة تكفي لإجراء تحليل رقمي كامل.',basis:[`${engagement.documents.length} مستند مسجل`],asks:[{title:selectedRecipePlan?.nextRequirement?.title??'تحديد المستند المالي الأساسي المطلوب',priority:'high'}]}];engagement=recordCouncilRound(engagement,{positions,conflicts:[],verdict:'needs-evidence',verdictText:'نحتاج بيانات أو مستندًا أساسيًا قبل الاستنتاج.'}).engagement}else{const session=convene(councilInput());engagement=recordCouncilRound(engagement,{...session,positions:session.positions,conflicts:session.conflicts??[],verdict:session.verdict,verdictText:session.verdictText,consensus:session.consensus}).engagement}render()}
function renderCouncil(){const latest=engagement.councilRounds.at(-1);$('#councilSummary').innerHTML=latest?`<strong>${esc(latest.verdict?(councilVerdictLabel(latest.verdict)??latest.verdict):latest.label)}</strong><br>${esc(latest.verdictText??'تم تسجيل الجولة.')}`:'لم تُعقد أي جولة.';$('#roundTimeline').innerHTML=engagement.councilRounds.map((r,i)=>`<div class="round ${i===engagement.councilRounds.length-1?'current':''}"><strong>R${String(r.number).padStart(2,'0')}</strong><small>${(r.evidenceIds??[]).length} دليل<br>${(r.issueIds??[]).length} قضية</small></div>`).join('');$('#seatList').innerHTML=latest?.positions?.map(seat=>`<article class="seat" data-stance="${esc(seat.stance)}"><header><strong>${esc(seat.title)}</strong><span>${esc(stanceLabel(seat.stance))}</span></header><small>${esc(seat.domain??'')}</small><p>${esc(seat.statement)}</p>${seat.asks?.length?`<small>${seat.asks.length} طلب/سؤال</small>`:''}</article>`).join('')??''}
function renderRequests(){const metrics=evidenceRequestMetrics(engagement.requests);$('#requestMetrics').innerHTML=`<div><strong>${metrics.open}</strong><small>مفتوح</small></div><div><strong>${metrics.criticalOpen}</strong><small>حرج</small></div><div><strong>${metrics.satisfied}</strong><small>مستوفى</small></div>`;const target=$('#requestList');if(!engagement.requests.length){target.className='stack empty';target.textContent='لا توجد طلبات مفتوحة.';return}target.className='stack';target.innerHTML=engagement.requests.map(r=>`<article class="request"><header><strong>${esc(r.id)} · ${esc(r.title)}</strong><span class="priority-${esc(r.priority)}">${esc(r.status)}</span></header><small>طلبه: ${esc((r.requestedBy??[]).join('، '))} · التغطية ${r.coverage??0}%</small>${['requested','partial','received','under-review'].includes(r.status)?`<button class="secondary evidence-button" data-request-id="${esc(r.id)}">إضافة دليل لهذا الطلب</button>`:''}</article>`).join('');document.querySelectorAll('.evidence-button').forEach(b=>b.addEventListener('click',()=>openEvidenceDialog(b.dataset.requestId)))}
function openEvidenceDialog(requestId){activeRequestId=requestId;const r=engagement.requests.find(i=>i.id===requestId);$('#evidenceRequestTitle').textContent=`${r.id} — ${r.title}`;$('#evidenceFile').value='';$('#evidenceDialog').showModal()}
async function saveEvidence(event){event.preventDefault();const file=$('#evidenceFile').files[0];if(!file||!activeRequestId)return;const request=engagement.requests.find(i=>i.id===activeRequestId),hash=await sha256(file),docId=nextDocumentId();engagement.documents.push({id:docId,name:file.name,type:classifyDocument(file),mime:file.type,size:file.size,sha256:hash,version:1,status:'classified',createdAt:new Date().toISOString()});const criteriaSatisfied=[];if($('#criterionRelevance').checked)criteriaSatisfied.push('relevance');if($('#criterionPeriod').checked)criteriaSatisfied.push('period');engagement=ingestEvidenceBatch(engagement,[{title:file.name,documentIds:[docId],requestIds:[activeRequestId],issueIds:request.issueId?[request.issueId]:[],reviewStatus:'received',criteriaSatisfied,sourceType:$('#evidenceSource').value,sha256:hash,documentDate:new Date().toISOString().slice(0,10),riskIds:request.riskIds??[]}]).engagement;Object.assign(engagement.evidence.at(-1),{sha256:hash,documentDate:new Date().toISOString().slice(0,10),riskIds:request.riskIds??[]});$('#evidenceDialog').close();render()}
function proposeDemoAdjustment(){if(!analysis?.rows?.length)return;const debit=analysis.rows.find(r=>r.debit>0n),credit=analysis.rows.find(r=>r.credit>0n);if(!debit||!credit)return;engagement.adjustments=proposeAdjustment(engagement.adjustments,{title:'تسوية تجريبية محكومة',type:'RECLASSIFICATION',rationale:'إثبات عمل Adjustment Ledger دون تعديل الميزان الأصلي.',standards:['IAS 1'],issueId:engagement.issues[0]?.id??null,councilRoundId:engagement.councilRounds.at(-1)?.id??null,lines:[{accountId:debit.id,code:debit.code,accountName:debit.name,side:'debit',amountMinor:100000n},{accountId:credit.id,code:credit.code,accountName:credit.name,side:'credit',amountMinor:100000n}]});engagement.stage=deriveEngagementStage(engagement);render()}
function acceptAdjustment(id){engagement.adjustments=decideAdjustment(engagement.adjustments,id,{decision:'accepted',actor:'المراجع البشري',rationale:'اعتماد تجريبي من واجهة V5'});const adjusted=buildAdjustedTrialBalance(analysis.rows,engagement.adjustments);if(!adjusted.balanced)throw new Error('Adjusted TB must stay balanced');render()}
function renderAdjustments(){const target=$('#adjustmentList');if(!engagement.adjustments.length){target.className='stack empty';target.textContent='لا توجد تسويات.';return}target.className='stack';target.innerHTML=engagement.adjustments.map(item=>`<article class="adjustment"><header><strong>${esc(item.id)} · ${esc(item.title)}</strong><span>${esc(item.status)}</span></header><small>مدين ${money(item.debitMinor)} · دائن ${money(item.creditMinor)} · ${esc(item.type)}</small><p>${esc(item.rationale)}</p>${item.status==='proposed'?`<button class="secondary accept-adjustment" data-id="${esc(item.id)}">اعتماد بشري تجريبي</button>`:''}</article>`).join('');document.querySelectorAll('.accept-adjustment').forEach(b=>b.addEventListener('click',()=>acceptAdjustment(b.dataset.id)))}
function renderTraceability(){const graph=buildEngagementTraceability(engagement),metrics=traceabilityMetrics(graph);$('#traceMetrics').innerHTML=`<div><strong>${metrics.nodes}</strong><small>عقدة</small></div><div><strong>${metrics.edges}</strong><small>رابط</small></div><div><strong>${metrics.isolated.length}</strong><small>معزول</small></div>`;const lastReport=engagement.reports.at(-1),lastAdjustment=engagement.adjustments.at(-1),target=lastReport?.id??lastAdjustment?.id;if(!target){$('#tracePreview').textContent='المستندات والطلبات والجولات مسجلة؛ أضف تسوية أو تقريرًا لرؤية مسار أعمق.';return}$('#tracePreview').innerHTML=traceAncestors(graph,target).slice(0,3).map(path=>path.map(n=>`<strong>${esc(n.id)}</strong>`).join(' ← ')).join('<br>')}
function buildDraft(){if(!selectedRecipePlan?.understood)return;const sourceIds=[...engagement.documents.map(d=>d.id),...engagement.evidence.map(e=>e.id),...engagement.adjustments.filter(a=>a.status==='accepted').map(a=>a.id),...engagement.councilRounds.slice(-1).map(r=>r.id)],id=`RPT-${String(engagement.reports.length+1).padStart(3,'0')}`;engagement.reports.push({id,title:selectedRecipePlan.recipe.title,type:selectedRecipePlan.recipe.id,version:engagement.reports.length+1,status:'draft',sourceIds,createdAt:new Date().toISOString(),sections:selectedRecipePlan.recipe.sections});engagement.stage=deriveEngagementStage(engagement);render()}
function renderReport(report=engagement.reports.at(-1),readiness=reportReadiness(engagement)){if(!report){$('#reportOutline').innerHTML='';return}$('#reportOutline').innerHTML=report.sections.map((s,i)=>`<button>${String(i+1).padStart(2,'0')} · ${esc(s)}</button>`).join('');const latest=engagement.councilRounds.at(-1),req=evidenceRequestMetrics(engagement.requests),accepted=engagement.adjustments.filter(a=>a.status==='accepted');$('#reportPaper').innerHTML=`<div class="paper-brand">KOSIF</div><p>مسودة · ${esc(report.id)} · v${report.version}</p><h1>${esc(report.title)}</h1><p>${esc(engagement.entity)}<br>${esc(engagement.period)}</p><h2>ملخص حالة الارتباط</h2><p>جاهزية الإصدار الحالية ${readiness.score}%. تم تسجيل ${engagement.documents.length} مستندًا، وعقد ${engagement.councilRounds.length} جولة مجلس، ويوجد ${req.open} طلب دليل مفتوح.</p><h2>المجلس</h2><p>${esc(latest?.verdictText??'لا توجد جولة مجلس.')}</p><h2>التسويات</h2><p>${accepted.length?`تم اعتماد ${accepted.length} تسوية محكومة بإجمالي آخر قيد ${money(accepted.at(-1).debitMinor)}.`:'لا توجد تسويات معتمدة.'}</p><h2>حدود المسودة</h2><p>${readiness.ready?'اجتازت المسودة بوابات الجاهزية البرمجية الحالية؛ يبقى الاعتماد المهني البشري.':`المسودة ليست جاهزة للإصدار. توجد ${readiness.blockers.length} موانع حرجة و${readiness.openRequests} طلبات أدلة مفتوحة.`}</p>`;$('#reportInspector').innerHTML=`<strong>Inspector</strong><p>${report.sourceIds.length?`المصادر: ${report.sourceIds.slice(0,10).map(esc).join('، ')}${report.sourceIds.length>10?'…':''}`:'لا توجد مصادر مرتبطة.'}</p><p>Trace sources: ${report.sourceIds.length}</p><p>Status: ${esc(report.status)}</p>`}
function render(){engagement.stage=deriveEngagementStage(engagement);renderNow();renderDocuments();renderRecipe();renderCouncil();renderRequests();renderAdjustments();renderTraceability();if(engagement.reports.length)renderReport()}
$('#documentInput').addEventListener('change',async e=>{for(const file of e.target.files)await registerFile(file);e.target.value='';render()});$('#demoButton').addEventListener('click',loadDemo);$('#reviewDocumentCard').addEventListener('click',()=>$('#documentInput').click());$('#buildReportCard').addEventListener('click',()=>$('#recipeInput').focus());$('#recipeForm').addEventListener('submit',e=>{e.preventDefault();selectedRecipePlan=buildReportPlan($('#recipeInput').value,{categories:currentCategories(),documentTypes:currentDocumentTypes()});renderRecipe()});$('#runCouncilButton').addEventListener('click',runCouncil);$('#evidenceForm').addEventListener('submit',saveEvidence);$('#proposeAdjustmentButton').addEventListener('click',proposeDemoAdjustment);$('#buildDraftButton').addEventListener('click',buildDraft);render();
