-- Generated by scripts/generate-d1-guards.mjs.
-- Historical engagement records are append-only; audit_log remains insertable after archive.
CREATE TRIGGER engagements_no_delete
BEFORE DELETE ON engagements
BEGIN
  SELECT RAISE(ABORT, 'engagements_cannot_be_deleted');
END;
--> statement-breakpoint
CREATE TRIGGER engagements_archived_no_update
BEFORE UPDATE ON engagements
WHEN OLD.archived_at IS NOT NULL
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER engagements_identity_no_update
BEFORE UPDATE ON engagements
WHEN OLD.id <> NEW.id
  OR OLD.tenant_id <> NEW.tenant_id
  OR OLD.framework <> NEW.framework
  OR OLD.ruleset_version <> NEW.ruleset_version
  OR OLD.period_start <> NEW.period_start
  OR OLD.period_end <> NEW.period_end
BEGIN
  SELECT RAISE(ABORT, 'engagement_identity_is_immutable');
END;
--> statement-breakpoint
CREATE TRIGGER source_files_no_update
BEFORE UPDATE ON source_files
BEGIN
  SELECT RAISE(ABORT, 'source_files_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER source_files_no_delete
BEFORE DELETE ON source_files
BEGIN
  SELECT RAISE(ABORT, 'source_files_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER rejected_rows_no_update
BEFORE UPDATE ON rejected_rows
BEGIN
  SELECT RAISE(ABORT, 'rejected_rows_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER rejected_rows_no_delete
BEFORE DELETE ON rejected_rows
BEGIN
  SELECT RAISE(ABORT, 'rejected_rows_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER accounts_no_update
BEFORE UPDATE ON accounts
BEGIN
  SELECT RAISE(ABORT, 'accounts_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER accounts_no_delete
BEFORE DELETE ON accounts
BEGIN
  SELECT RAISE(ABORT, 'accounts_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER trial_balance_lines_no_update
BEFORE UPDATE ON trial_balance_lines
BEGIN
  SELECT RAISE(ABORT, 'trial_balance_lines_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER trial_balance_lines_no_delete
BEFORE DELETE ON trial_balance_lines
BEGIN
  SELECT RAISE(ABORT, 'trial_balance_lines_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER journal_entries_no_update
BEFORE UPDATE ON journal_entries
BEGIN
  SELECT RAISE(ABORT, 'journal_entries_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER journal_entries_no_delete
BEFORE DELETE ON journal_entries
BEGIN
  SELECT RAISE(ABORT, 'journal_entries_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER journal_lines_no_update
BEFORE UPDATE ON journal_lines
BEGIN
  SELECT RAISE(ABORT, 'journal_lines_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER journal_lines_no_delete
BEFORE DELETE ON journal_lines
BEGIN
  SELECT RAISE(ABORT, 'journal_lines_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER mapping_sets_no_update
BEFORE UPDATE ON mapping_sets
BEGIN
  SELECT RAISE(ABORT, 'mapping_sets_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER mapping_sets_no_delete
BEFORE DELETE ON mapping_sets
BEGIN
  SELECT RAISE(ABORT, 'mapping_sets_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER mapping_rules_no_update
BEFORE UPDATE ON mapping_rules
BEGIN
  SELECT RAISE(ABORT, 'mapping_rules_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER mapping_rules_no_delete
BEFORE DELETE ON mapping_rules
BEGIN
  SELECT RAISE(ABORT, 'mapping_rules_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER calculation_runs_no_update
BEFORE UPDATE ON calculation_runs
BEGIN
  SELECT RAISE(ABORT, 'calculation_runs_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER calculation_runs_no_delete
BEFORE DELETE ON calculation_runs
BEGIN
  SELECT RAISE(ABORT, 'calculation_runs_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER derivations_no_update
BEFORE UPDATE ON derivations
BEGIN
  SELECT RAISE(ABORT, 'derivations_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER derivations_no_delete
BEFORE DELETE ON derivations
BEGIN
  SELECT RAISE(ABORT, 'derivations_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER provenance_nodes_no_update
BEFORE UPDATE ON provenance_nodes
BEGIN
  SELECT RAISE(ABORT, 'provenance_nodes_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER provenance_nodes_no_delete
BEFORE DELETE ON provenance_nodes
BEGIN
  SELECT RAISE(ABORT, 'provenance_nodes_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER derivation_inputs_no_update
BEFORE UPDATE ON derivation_inputs
BEGIN
  SELECT RAISE(ABORT, 'derivation_inputs_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER derivation_inputs_no_delete
BEFORE DELETE ON derivation_inputs
BEGIN
  SELECT RAISE(ABORT, 'derivation_inputs_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER figures_no_update
BEFORE UPDATE ON figures
BEGIN
  SELECT RAISE(ABORT, 'figures_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER figures_no_delete
BEFORE DELETE ON figures
BEGIN
  SELECT RAISE(ABORT, 'figures_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER facts_no_update
BEFORE UPDATE ON facts
BEGIN
  SELECT RAISE(ABORT, 'facts_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER facts_no_delete
BEFORE DELETE ON facts
BEGIN
  SELECT RAISE(ABORT, 'facts_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER je_test_runs_no_update
BEFORE UPDATE ON je_test_runs
BEGIN
  SELECT RAISE(ABORT, 'je_test_runs_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER je_test_runs_no_delete
BEFORE DELETE ON je_test_runs
BEGIN
  SELECT RAISE(ABORT, 'je_test_runs_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER findings_no_update
BEFORE UPDATE ON findings
BEGIN
  SELECT RAISE(ABORT, 'findings_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER findings_no_delete
BEFORE DELETE ON findings
BEGIN
  SELECT RAISE(ABORT, 'findings_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER finding_dispositions_no_update
BEFORE UPDATE ON finding_dispositions
BEGIN
  SELECT RAISE(ABORT, 'finding_dispositions_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER finding_dispositions_no_delete
BEFORE DELETE ON finding_dispositions
BEGIN
  SELECT RAISE(ABORT, 'finding_dispositions_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER materiality_versions_no_update
BEFORE UPDATE ON materiality_versions
BEGIN
  SELECT RAISE(ABORT, 'materiality_versions_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER materiality_versions_no_delete
BEFORE DELETE ON materiality_versions
BEGIN
  SELECT RAISE(ABORT, 'materiality_versions_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER misstatements_no_update
BEFORE UPDATE ON misstatements
BEGIN
  SELECT RAISE(ABORT, 'misstatements_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER misstatements_no_delete
BEFORE DELETE ON misstatements
BEGIN
  SELECT RAISE(ABORT, 'misstatements_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER opinion_assessments_no_update
BEFORE UPDATE ON opinion_assessments
BEGIN
  SELECT RAISE(ABORT, 'opinion_assessments_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER opinion_assessments_no_delete
BEFORE DELETE ON opinion_assessments
BEGIN
  SELECT RAISE(ABORT, 'opinion_assessments_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER ai_proposals_no_update
BEFORE UPDATE ON ai_proposals
BEGIN
  SELECT RAISE(ABORT, 'ai_proposals_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER ai_proposals_no_delete
BEFORE DELETE ON ai_proposals
BEGIN
  SELECT RAISE(ABORT, 'ai_proposals_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER ai_claims_no_update
BEFORE UPDATE ON ai_claims
BEGIN
  SELECT RAISE(ABORT, 'ai_claims_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER ai_claims_no_delete
BEFORE DELETE ON ai_claims
BEGIN
  SELECT RAISE(ABORT, 'ai_claims_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER ai_reviews_no_update
BEFORE UPDATE ON ai_reviews
BEGIN
  SELECT RAISE(ABORT, 'ai_reviews_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER ai_reviews_no_delete
BEFORE DELETE ON ai_reviews
BEGIN
  SELECT RAISE(ABORT, 'ai_reviews_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER audit_log_no_update
BEFORE UPDATE ON audit_log
BEGIN
  SELECT RAISE(ABORT, 'audit_log_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER audit_log_no_delete
BEFORE DELETE ON audit_log
BEGIN
  SELECT RAISE(ABORT, 'audit_log_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER fs_lines_no_update
BEFORE UPDATE ON fs_lines
BEGIN
  SELECT RAISE(ABORT, 'fs_lines_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER fs_lines_no_delete
BEFORE DELETE ON fs_lines
BEGIN
  SELECT RAISE(ABORT, 'fs_lines_is_append_only');
END;
--> statement-breakpoint
CREATE TRIGGER source_files_archived_insert_guard
BEFORE INSERT ON source_files
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER rejected_rows_archived_insert_guard
BEFORE INSERT ON rejected_rows
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER accounts_archived_insert_guard
BEFORE INSERT ON accounts
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER trial_balance_lines_archived_insert_guard
BEFORE INSERT ON trial_balance_lines
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER journal_entries_archived_insert_guard
BEFORE INSERT ON journal_entries
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER journal_lines_archived_insert_guard
BEFORE INSERT ON journal_lines
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER mapping_sets_archived_insert_guard
BEFORE INSERT ON mapping_sets
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER mapping_rules_archived_insert_guard
BEFORE INSERT ON mapping_rules
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER calculation_runs_archived_insert_guard
BEFORE INSERT ON calculation_runs
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER derivations_archived_insert_guard
BEFORE INSERT ON derivations
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER provenance_nodes_archived_insert_guard
BEFORE INSERT ON provenance_nodes
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER derivation_inputs_archived_insert_guard
BEFORE INSERT ON derivation_inputs
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER figures_archived_insert_guard
BEFORE INSERT ON figures
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER facts_archived_insert_guard
BEFORE INSERT ON facts
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER je_test_runs_archived_insert_guard
BEFORE INSERT ON je_test_runs
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER findings_archived_insert_guard
BEFORE INSERT ON findings
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER finding_dispositions_archived_insert_guard
BEFORE INSERT ON finding_dispositions
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER materiality_versions_archived_insert_guard
BEFORE INSERT ON materiality_versions
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER misstatements_archived_insert_guard
BEFORE INSERT ON misstatements
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER opinion_assessments_archived_insert_guard
BEFORE INSERT ON opinion_assessments
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER ai_proposals_archived_insert_guard
BEFORE INSERT ON ai_proposals
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER ai_claims_archived_insert_guard
BEFORE INSERT ON ai_claims
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
--> statement-breakpoint
CREATE TRIGGER ai_reviews_archived_insert_guard
BEFORE INSERT ON ai_reviews
WHEN EXISTS (
  SELECT 1 FROM engagements
  WHERE id = NEW.engagement_id AND archived_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'archived_engagement_is_read_only');
END;
