/** KOSIF V5 — immutable balanced adjustment ledger. */
const toBigInt=v=>typeof v==='bigint'?v:BigInt(v??0),abs=v=>v<0n?-v:v;
function nextAdjustmentId(existing=[]){const max=existing.reduce((h,i)=>{const m=String(i.id??'').match(/^AJ-(\d+)$/);return m?Math.max(h,Number(m[1])):h},0);return `AJ-${String(max+1).padStart(4,'0')}`}
export function normalizeAdjustmentLine(line={}){const side=line.side==='credit'?'credit':'debit',amountMinor=abs(toBigInt(line.amountMinor));if(amountMinor===0n)throw new RangeError('Adjustment line amount must be greater than zero');if(!line.accountId&&!line.code)throw new TypeError('Adjustment line requires accountId or code');return{accountId:line.accountId??null,code:line.code??null,accountName:line.accountName??null,side,amountMinor}}
export function validateAdjustment(adjustment={}){const lines=(adjustment.lines??[]).map(normalizeAdjustmentLine);if(lines.length<2)return{valid:false,reason:'Adjustment requires at least two lines',debitMinor:0n,creditMinor:0n};const debitMinor=lines.filter(l=>l.side==='debit').reduce((s,l)=>s+l.amountMinor,0n),creditMinor=lines.filter(l=>l.side==='credit').reduce((s,l)=>s+l.amountMinor,0n);return{valid:debitMinor===creditMinor&&debitMinor>0n,reason:debitMinor===creditMinor?null:'Debits must equal credits',debitMinor,creditMinor,lines}}
export function proposeAdjustment(existing=[],input={},{proposedAt=new Date().toISOString()}={}){const id=input.id??nextAdjustmentId(existing),v=validateAdjustment(input);if(!v.valid)throw new RangeError(v.reason);const adjustment={id,issueId:input.issueId??null,type:input.type??'CORRECTION',title:input.title??'تسوية مقترحة',rationale:input.rationale??'',standards:[...new Set(input.standards??[])],evidenceIds:[...new Set(input.evidenceIds??[])],councilRoundId:input.councilRoundId??null,lines:v.lines,debitMinor:v.debitMinor,creditMinor:v.creditMinor,status:'proposed',proposedBy:input.proposedBy??'KOSIF Council',proposedAt,decision:null,version:Number(input.version??1)};return[...existing.map(i=>structuredClone(i)),adjustment]}
export function decideAdjustment(existing=[],adjustmentId,{decision,actor,rationale,decidedAt=new Date().toISOString()}={}){if(!['accepted','rejected'].includes(decision))throw new RangeError('decision must be accepted or rejected');if(!actor||!String(actor).trim())throw new TypeError('actor is required');if(!rationale||!String(rationale).trim())throw new TypeError('rationale is required');let found=false;const next=existing.map(i=>{if(i.id!==adjustmentId)return structuredClone(i);found=true;if(!['proposed','challenged','modified'].includes(i.status))throw new RangeError(`Adjustment ${adjustmentId} is not awaiting decision`);return{...structuredClone(i),status:decision,decision:{decision,actor:String(actor),rationale:String(rationale),decidedAt}}});if(!found)throw new RangeError(`Adjustment not found: ${adjustmentId}`);return next}
function rowKey(row={}){return String(row.id??row.accountId??row.code??'')}
export function buildAdjustedTrialBalance(originalRows=[],adjustments=[]){const rows=originalRows.map(r=>({...structuredClone(r),debit:toBigInt(r.debit??0),credit:toBigInt(r.credit??0)})),byId=new Map(rows.map(r=>[rowKey(r),r])),accepted=adjustments.filter(a=>a.status==='accepted');for(const a of accepted){const v=validateAdjustment(a);if(!v.valid)throw new RangeError(`Invalid accepted adjustment ${a.id}: ${v.reason}`);for(const line of v.lines){const key=String(line.accountId??line.code);let row=byId.get(key);if(!row){row={id:line.accountId??`ADJ-${line.code}`,code:line.code??'',name:line.accountName??'حساب تسوية',debit:0n,credit:0n,source:'adjustment-ledger'};rows.push(row);byId.set(rowKey(row),row);if(line.code)byId.set(String(line.code),row)}if(line.side==='debit')row.debit+=line.amountMinor;else row.credit+=line.amountMinor}}
 const totalDebit=rows.reduce((s,r)=>s+r.debit,0n),totalCredit=rows.reduce((s,r)=>s+r.credit,0n);return{rows,totalDebit,totalCredit,imbalance:totalDebit-totalCredit,balanced:totalDebit===totalCredit,appliedAdjustmentIds:accepted.map(a=>a.id)}}
export function adjustmentImpact(adjustment={}){const v=validateAdjustment(adjustment);if(!v.valid)throw new RangeError(v.reason);const byAccount=new Map();for(const line of v.lines){const key=String(line.accountId??line.code),cur=byAccount.get(key)??{accountId:line.accountId,code:line.code,accountName:line.accountName,debitMinor:0n,creditMinor:0n};if(line.side==='debit')cur.debitMinor+=line.amountMinor;else cur.creditMinor+=line.amountMinor;byAccount.set(key,cur)}return{debitMinor:v.debitMinor,creditMinor:v.creditMinor,accounts:[...byAccount.values()]}}
