import { parseMoneyMinor } from '../engine.js';
import { store, esc, money } from './continuous-store.js';
import { equityReadiness } from './equity-engine.js';
import { recordEquityVersion, latestEquityVersion } from './equity-workflow.js';

const $=s=>document.querySelector(s);let refresh=()=>{};
function recipeId(){return store.recipePlan?.recipe?.id||store.engagement.reports.at(-1)?.recipeId||''}
function draft(){return store.engagement.equityDraft||{components:[],movements:[]}}
function setDraft(value){store.engagement.equityDraft=value;store.engagement.updatedAt=new Date().toISOString()}
function parseSources(text=''){return[...new Set(String(text).split(',').map(x=>x.trim()).filter(Boolean))]}
function sourceOptions(){return [...store.engagement.documents.map(x=>x.id),...store.engagement.evidence.map(x=>x.id)]}
function ensureUi(){const cash=$('#cashFlowWorkspace'),disclosures=$('#disclosureWorkspace'),report=$('.report-panel'),anchor=disclosures||cash||report;if(!anchor||$('#equityWorkspace'))return;anchor.insertAdjacentHTML('beforebegin',`<section class="panel equity-workspace" id="equityWorkspace" hidden><div class="section-head"><div><p class="eyebrow">CHANGES IN EQUITY WORKBENCH</p><h2>قائمة التغيرات في حقوق الملكية</h2></div><div id="equityStatus" class="equity-status">غير جاهزة</div></div><p class="equity-note">أضف مكونات حقوق الملكية وأرصدة أول/آخر الفترة، ثم اربط كل حركة بالمكوّن ومصدر داخل الارتباط. يجب أن يتصالح كل مكوّن منفردًا قبل الاعتماد.</p><form id="equityComponentForm" class="equity-component-form"><input id="equityComponentLabel" required placeholder="المكوّن: رأس المال / أرباح مبقاة"><input id="equityOpening" required inputmode="decimal" placeholder="أول الفترة"><input id="equityOpeningSources" required placeholder="مصادر الافتتاح" list="equitySourceIds"><input id="equityClosing" required inputmode="decimal" placeholder="آخر الفترة"><input id="equityClosingSources" required placeholder="مصادر الختام" list="equitySourceIds"><button class="secondary">إضافة مكوّن</button></form><form id="equityMovementForm" class="equity-movement-form"><select id="equityMovementComponent" required></select><input id="equityMovementLabel" required placeholder="وصف الحركة"><select id="equityMovementKind"><option value="profit-or-loss">ربح/خسارة الفترة</option><option value="dividend">توزيعات</option><option value="capital-issue">إصدار رأس مال</option><option value="repurchase">إعادة شراء</option><option value="reserve-transfer">تحويل احتياطي</option><option value="oci">دخل شامل آخر</option><option value="prior-period-adjustment">تعديل فترة سابقة</option><option value="other">أخرى</option></select><select id="equityMovementDirection"><option value="increase">زيادة</option><option value="decrease">نقص</option></select><input id="equityMovementAmount" required inputmode="decimal" placeholder="المبلغ"><input id="equityMovementSources" required placeholder="Source IDs" list="equitySourceIds"><button class="secondary">إضافة حركة</button></form><datalist id="equitySourceIds"></datalist><div id="equitySummary" class="equity-summary"></div><div id="equityComponentList" class="equity-component-list"></div><div id="equityMovementList" class="equity-movement-list"></div><div class="equity-actions"><button type="button" id="approveEquityVersion" class="primary">اعتماد نسخة حقوق الملكية</button></div></section>`);$('#equityComponentForm').onsubmit=addComponent;$('#equityMovementForm').onsubmit=addMovement;$('#approveEquityVersion').onclick=approveVersion}
function addComponent(event){event.preventDefault();const d=draft();try{const component={id:`EQC-${String(d.components.length+1).padStart(3,'0')}`,label:$('#equityComponentLabel').value.trim(),openingMinor:parseMoneyMinor($('#equityOpening').value),closingMinor:parseMoneyMinor($('#equityClosing').value),openingSourceIds:parseSources($('#equityOpeningSources').value),closingSourceIds:parseSources($('#equityClosingSources').value)};d.components=[...d.components,component];setDraft(d);event.target.reset();refresh()}catch(e){alert(e.message)}}
function addMovement(event){event.preventDefault();const d=draft();try{const amount=parseMoneyMinor($('#equityMovementAmount').value);if(amount<0n)throw new RangeError('استخدم زيادة/نقص بدل مبلغ سالب.');d.movements=[...d.movements,{id:`EQM-${String(d.movements.length+1).padStart(4,'0')}`,componentId:$('#equityMovementComponent').value,label:$('#equityMovementLabel').value.trim(),kind:$('#equityMovementKind').value,direction:$('#equityMovementDirection').value,amountMinor:amount,sourceIds:parseSources($('#equityMovementSources').value)}];setDraft(d);event.target.reset();refresh()}catch(e){alert(e.message)}}
function removeMovement(id){const d=draft();d.movements=d.movements.filter(x=>x.id!==id);setDraft(d);refresh()}
function removeComponent(id){const d=draft();if(d.movements.some(x=>x.componentId===id)){alert('احذف الحركات المرتبطة بالمكوّن أولًا.');return}d.components=d.components.filter(x=>x.id!==id);setDraft(d);refresh()}
function approveVersion(){const rationale=prompt('دوّن أساس اعتماد قائمة التغيرات في حقوق الملكية ومصادرها:');if(!rationale?.trim())return;try{store.engagement=recordEquityVersion(store.engagement,draft(),{actor:'المراجع البشري',actorType:'human',rationale:rationale.trim()}).engagement;refresh()}catch(e){alert(`${e.message}${e.blockers?.length?`\n${e.blockers.map(b=>`• ${b.message}`).join('\n')}`:''}`)}}
export function initEquity({renderAll=()=>{}}={}){refresh=renderAll;ensureUi()}
export function renderEquity(){ensureUi();const panel=$('#equityWorkspace');if(!panel)return;const show=recipeId()==='full-financial-statements';panel.hidden=!show;if(!show)return;const d=draft(),readiness=equityReadiness(d),latest=latestEquityVersion(store.engagement),st=readiness.statement;$('#equityStatus').textContent=latest?`${latest.id} معتمدة`:readiness.ready?'جاهزة للاعتماد':'غير جاهزة';$('#equityStatus').className=`equity-status ${latest?'approved':readiness.ready?'ready':'blocked'}`;$('#equitySourceIds').innerHTML=sourceOptions().map(id=>`<option value="${esc(id)}"></option>`).join('');$('#equityMovementComponent').innerHTML=d.components.map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join('');$('#equityMovementForm').querySelector('button').disabled=!d.components.length;$('#equitySummary').innerHTML=st?`<div><strong>${money(st.openingTotalMinor)}</strong><small>أول الفترة</small></div><div><strong>${money(st.movementTotalMinor)}</strong><small>صافي الحركة</small></div><div><strong>${money(st.closingTotalMinor)}</strong><small>آخر الفترة</small></div><div><strong>${money(st.reconciliationDeltaMinor)}</strong><small>فرق التسوية</small></div>`:'';$('#equityComponentList').innerHTML=st?.components.length?st.components.map(c=>`<article class="equity-component ${c.reconciled?'reconciled':'unreconciled'}"><div><strong>${esc(c.id)} · ${esc(c.label)}</strong><small>${money(c.openingMinor)} → ${money(c.closingMinor)}</small></div><span>حركة ${money(c.movementMinor)} · فرق ${money(c.reconciliationDeltaMinor)}</span><button type="button" class="ghost equity-remove-component" data-id="${esc(c.id)}">حذف</button></article>`).join(''):'<div class="empty">أضف مكونات حقوق الملكية أولًا.</div>';$('#equityMovementList').innerHTML=d.movements.length?d.movements.map(m=>`<article><div><strong>${esc(m.id)} · ${esc(m.label)}</strong><small>${esc(m.kind)} · ${esc(m.componentId)}</small></div><span>${m.direction==='increase'?'+':'−'} ${money(m.amountMinor)}</span><small>${esc((m.sourceIds||[]).join(' · '))}</small><button type="button" class="ghost equity-remove-movement" data-id="${esc(m.id)}">حذف</button></article>`).join(''):'<div class="empty">لا توجد حركات حقوق ملكية.</div>';document.querySelectorAll('.equity-remove-component').forEach(b=>b.onclick=()=>removeComponent(b.dataset.id));document.querySelectorAll('.equity-remove-movement').forEach(b=>b.onclick=()=>removeMovement(b.dataset.id));const button=$('#approveEquityVersion');button.disabled=!readiness.ready;button.textContent=readiness.ready?'اعتماد نسخة متصالحة':`${readiness.blockers.length} مانع قبل الاعتماد`}
