/** KOSIF V5 — governed disclosure/notes candidate engine. */
const REVIEW_STATUSES=new Set(['applicable','not-applicable','prepared','reviewed']);
const OPEN_ISSUES=new Set(['open','investigating','management-response','challenged']);
const norm=v=>String(v??'').trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[\u064B-\u065F\u0670]/g,'').replace(/\s+/g,' ');
const uniq=v=>[...new Set((v||[]).filter(Boolean))];
const TOPICS=Object.freeze([
  {id:'BASIS_POLICIES',title:'أساس الإعداد والسياسات المحاسبية الجوهرية',standards:['IAS 1','IAS 8'],always:true},
  {id:'JUDGEMENTS_ESTIMATES',title:'الأحكام والتقديرات ومصادر عدم التأكد',standards:['IAS 1','IAS 8'],issue:/estimate|impair|valuation|تقدير|تقييم|انخفاض|مخصص/i},
  {id:'REVENUE',title:'الإيرادات والعقود مع العملاء',standards:['IFRS 15'],categories:['عقود وإيرادات','إيرادات']},
  {id:'FINANCIAL_INSTRUMENTS',title:'الأدوات المالية ومخاطر الائتمان والسيولة',standards:['IFRS 7','IFRS 9'],categories:['نقدية وبنوك','ذمم مدينة','استثمارات وأدوات مالية','قروض وتمويل']},
  {id:'INVENTORIES',title:'المخزون والقياس وصافي القيمة القابلة للتحقق',standards:['IAS 2'],categories:['مخزون']},
  {id:'PPE',title:'الممتلكات والآلات والمعدات والإهلاك',standards:['IAS 16'],categories:['أصول ثابتة']},
  {id:'INTANGIBLES_IMPAIRMENT',title:'الأصول غير الملموسة والانخفاض في القيمة',standards:['IAS 36','IAS 38'],categories:['أصول غير ملموسة']},
  {id:'LEASES',title:'الإيجارات وأصول حق الاستخدام والتزامات الإيجار',standards:['IFRS 16'],categories:['إيجارات']},
  {id:'TAX_ZAKAT',title:'الضرائب والزكاة والأرصدة ذات الصلة',standards:['IAS 12'],categories:['ضرائب وزكاة']},
  {id:'PROVISIONS_CONTINGENCIES',title:'المخصصات والالتزامات المحتملة',standards:['IAS 37'],categories:['مخصصات ومنافع موظفين'],issue:/legal|lawsuit|provision|conting|قانون|دعوى|مخصص|التزام محتمل/i},
  {id:'EMPLOYEE_BENEFITS',title:'منافع الموظفين',standards:['IAS 19'],categories:['مخصصات ومنافع موظفين']},
  {id:'EQUITY_CAPITAL',title:'حقوق الملكية ورأس المال',standards:['IAS 1','IAS 32'],categories:['حقوق ملكية']},
  {id:'RELATED_PARTIES',title:'الأطراف ذات العلاقة والمعاملات المرتبطة',standards:['IAS 24'],issue:/related party|طرف ذي علاقه|طرف ذات علاقه|اطراف ذات علاقه|أطراف ذات علاقة/i},
  {id:'GOING_CONCERN',title:'الاستمرارية وعدم التأكد الجوهري عند انطباقه',standards:['IAS 1'],issue:/going concern|استمراري|سيول|تمويل مستمر|covenant/i},
  {id:'SUBSEQUENT_EVENTS',title:'الأحداث اللاحقة',standards:['IAS 10'],issue:/subsequent|حدث لاحق|احداث لاحقه|أحداث لاحقة/i}
]);
function latestByTopic(engagement={}){const map=new Map;for(const d of engagement.disclosureReviews||[])map.set(d.topicId,d);return map}
function topicTriggered(topic,rows,issues){if(topic.always)return{triggered:true,reasons:['متطلب أساسي للقوائم المالية الكاملة']};const reasons=[],cats=new Set(rows.map(r=>r.category).filter(Boolean));if(topic.categories?.some(c=>cats.has(c)))reasons.push(`ظهور فئة حساب: ${topic.categories.filter(c=>cats.has(c)).join('، ')}`);const standards=new Set(rows.flatMap(r=>r.standards||[]));if(topic.standards?.some(s=>standards.has(s)))reasons.push(`ربط حسابي بمعيار: ${topic.standards.filter(s=>standards.has(s)).join('، ')}`);const matchingIssues=issues.filter(i=>topic.issue?.test(`${i.title||''} ${i.rationale||''} ${(i.standards||[]).join(' ')}`));if(matchingIssues.length)reasons.push(`قضايا مرتبطة: ${matchingIssues.map(i=>i.id).join('، ')}`);return{triggered:reasons.length>0,reasons,issueIds:matchingIssues.map(i=>i.id)}}
export function disclosureCandidates({rows=[],engagement={},recipeId='full-financial-statements'}={}){if(recipeId!=='full-financial-statements')return[];const issues=(engagement.issues||[]).filter(i=>OPEN_ISSUES.has(i.status)),latest=latestByTopic(engagement),out=[];for(const topic of TOPICS){const trigger=topicTriggered(topic,rows,issues);if(!trigger.triggered)continue;const review=latest.get(topic.id)||null;out.push({id:`DSC-${topic.id}`,topicId:topic.id,title:topic.title,standards:[...topic.standards],triggerReasons:trigger.reasons||[],issueIds:trigger.issueIds||[],status:review?.status||'candidate',review,sourceIds:uniq([...(trigger.issueIds||[]),...rows.filter(r=>topic.categories?.includes(r.category)||topic.standards?.some(s=>(r.standards||[]).includes(s))).map(r=>r.id)])})}return out}
export function recordDisclosureReview(engagement={},input={},{at=new Date().toISOString()}={}){if(!TOPICS.some(t=>t.id===input.topicId))throw new RangeError('Unknown disclosure topic');if(!REVIEW_STATUSES.has(input.status))throw new RangeError('Invalid disclosure review status');if(input.actorType!=='human')throw new TypeError('Disclosure review requires actorType=human');if(!input.actor||!String(input.actor).trim())throw new TypeError('actor is required');if(!input.rationale||!String(input.rationale).trim())throw new TypeError('rationale is required');const next=structuredClone(engagement),previous=[...(next.disclosureReviews||[])].reverse().find(d=>d.topicId===input.topicId);if(input.status==='prepared'&&!previous?.status?.match(/applicable|prepared|reviewed/))throw new RangeError('Disclosure must be marked applicable before prepared');if(input.status==='reviewed'&&!previous?.status?.match(/prepared|reviewed/))throw new RangeError('Disclosure must be prepared before reviewed');const review={id:`DSR-${String((next.disclosureReviews||[]).length+1).padStart(4,'0')}`,topicId:input.topicId,status:input.status,actor:String(input.actor),actorType:'human',rationale:String(input.rationale),sourceIds:uniq(input.sourceIds),at,previousReviewId:previous?.id||null};next.disclosureReviews=[...(next.disclosureReviews||[]),review];next.updatedAt=at;return{engagement:next,review}}
export function disclosureStatus({rows=[],engagement={},recipeId='full-financial-statements'}={}){const candidates=disclosureCandidates({rows,engagement,recipeId}),resolved=candidates.filter(c=>['not-applicable','reviewed'].includes(c.status)),applicable=candidates.filter(c=>['applicable','prepared','reviewed'].includes(c.status));return{candidates,total:candidates.length,resolved:resolved.length,applicable:applicable.length,pending:candidates.length-resolved.length,ready:candidates.length>0&&resolved.length===candidates.length,score:candidates.length?Math.round(resolved.length/candidates.length*100):0}}
export function disclosureTopic(id){const t=TOPICS.find(x=>x.id===id);return t?structuredClone(t):null}
