/** KOSIF V5 — strict statement of changes in equity engine. */
const DIRECTIONS=new Set(['increase','decrease']);
const KINDS=new Set(['profit-or-loss','dividend','capital-issue','repurchase','reserve-transfer','oci','prior-period-adjustment','other']);
const uniq=v=>[...new Set((v||[]).map(String).map(x=>x.trim()).filter(Boolean))];
function minor(value,name){if(typeof value==='bigint')return value;if(typeof value==='number'&&Number.isInteger(value))return BigInt(value);const text=String(value??'').trim();if(!/^-?\d+$/.test(text))throw new TypeError(`${name} must be integer minor units`);return BigInt(text)}
export function normalizeEquityComponent(input={},index=0){const id=String(input.id||`EQC-${String(index+1).padStart(3,'0')}`),label=String(input.label||'مكوّن حقوق ملكية').trim();if(!label)throw new TypeError('Equity component label is required');return{id,label,openingMinor:minor(input.openingMinor,'openingMinor'),closingMinor:minor(input.closingMinor,'closingMinor'),openingSourceIds:uniq(input.openingSourceIds),closingSourceIds:uniq(input.closingSourceIds)}}
export function normalizeEquityMovement(input={},index=0){if(!DIRECTIONS.has(input.direction))throw new RangeError('Invalid equity movement direction');if(!KINDS.has(input.kind))throw new RangeError('Invalid equity movement kind');const amount=minor(input.amountMinor,'amountMinor');if(amount<0n)throw new RangeError('amountMinor must be non-negative');const componentId=String(input.componentId||'').trim();if(!componentId)throw new TypeError('componentId is required');return{id:String(input.id||`EQM-${String(index+1).padStart(4,'0')}`),componentId,label:String(input.label||'حركة حقوق ملكية').trim(),kind:input.kind,direction:input.direction,amountMinor:amount,sourceIds:uniq(input.sourceIds),note:String(input.note||'').trim()}}
export function buildEquityStatement({components=[],movements=[]}={}){const comps=components.map(normalizeEquityComponent),ids=new Set;for(const c of comps){if(ids.has(c.id))throw new RangeError(`Duplicate equity component: ${c.id}`);ids.add(c.id)}const moves=movements.map(normalizeEquityMovement);for(const m of moves)if(!ids.has(m.componentId))throw new RangeError(`Unknown equity component: ${m.componentId}`);const rows=comps.map(c=>{const linked=moves.filter(m=>m.componentId===c.id),movementMinor=linked.reduce((sum,m)=>sum+(m.direction==='increase'?m.amountMinor:-m.amountMinor),0n),calculatedClosingMinor=c.openingMinor+movementMinor,reconciliationDeltaMinor=c.closingMinor-calculatedClosingMinor;return{...c,movements:linked,movementMinor,calculatedClosingMinor,reconciliationDeltaMinor,reconciled:reconciliationDeltaMinor===0n}});const openingTotalMinor=rows.reduce((s,r)=>s+r.openingMinor,0n),movementTotalMinor=rows.reduce((s,r)=>s+r.movementMinor,0n),closingTotalMinor=rows.reduce((s,r)=>s+r.closingMinor,0n),calculatedClosingTotalMinor=openingTotalMinor+movementTotalMinor,reconciliationDeltaMinor=closingTotalMinor-calculatedClosingTotalMinor,unsupportedComponents=rows.filter(r=>!r.openingSourceIds.length||!r.closingSourceIds.length).map(r=>r.id),unsupportedMovements=moves.filter(m=>!m.sourceIds.length).map(m=>m.id);return{components:rows,movements:moves,openingTotalMinor,movementTotalMinor,closingTotalMinor,calculatedClosingTotalMinor,reconciliationDeltaMinor,reconciled:rows.length>0&&rows.every(r=>r.reconciled)&&reconciliationDeltaMinor===0n,sourceCoverage:{componentTotal:rows.length,unsupportedComponents,movementTotal:moves.length,unsupportedMovements,complete:rows.length>0&&unsupportedComponents.length===0&&unsupportedMovements.length===0}}}
export function equityReadiness(input={}){let statement;try{statement=buildEquityStatement(input)}catch(error){return{ready:false,statement:null,blockers:[{type:'invalid-input',message:error.message}]}}const blockers=[];if(!statement.components.length)blockers.push({type:'no-components',message:'لا توجد مكونات حقوق ملكية.'});if(statement.sourceCoverage.unsupportedComponents.length)blockers.push({type:'unsupported-components',message:`${statement.sourceCoverage.unsupportedComponents.length} مكوّن بلا مصادر افتتاح/ختام كاملة.`});if(statement.sourceCoverage.unsupportedMovements.length)blockers.push({type:'unsupported-movements',message:`${statement.sourceCoverage.unsupportedMovements.length} حركة بلا مصدر قابل للتتبع.`});if(!statement.reconciled)blockers.push({type:'reconciliation',message:`فرق تسوية حقوق الملكية ${statement.reconciliationDeltaMinor.toString()} بوحدة صغرى.`});return{ready:blockers.length===0,statement,blockers}}
export const EQUITY_MOVEMENT_KINDS=Object.freeze([...KINDS]);
