/** KOSIF V5 — intent-driven report recipes and adaptive evidence requirements. */
const requirement=(id,title,{priority='high',when=null,reason='',documentTypes=[]}={})=>({id,title,priority,when,reason,documentTypes});
export const REPORT_RECIPES=Object.freeze({
'statement-of-financial-position':{id:'statement-of-financial-position',title:'قائمة المركز المالي',aliases:['ميزانية','الميزانية','قائمة مركز مالي','المركز المالي','balance sheet','statement of financial position'],engagementType:'preparation',minimumInputs:[requirement('TB','ميزان المراجعة النهائي',{priority:'critical',reason:'الأساس الرقمي لبناء القائمة.',documentTypes:['trial-balance']}),requirement('COA','دليل الحسابات وربط الحسابات',{priority:'high',reason:'لاستكمال التصنيف والعرض.',documentTypes:['chart-of-accounts']})],conditionalInputs:[requirement('BANK','كشوف وتسويات البنوك',{when:['نقدية وبنوك'],reason:'لأن القائمة تحتوي أرصدة نقدية وبنكية.'}),requirement('AR','أعمار العملاء والتحصيلات اللاحقة',{when:['ذمم مدينة'],reason:'لدعم الوجود والتقييم وخسائر الائتمان المتوقعة.'}),requirement('INV','سجلات الجرد والتكلفة وNRV',{when:['مخزون'],reason:'لدعم الوجود والتقييم.'}),requirement('PPE','سجل الأصول الثابتة والإهلاك',{when:['أصول ثابتة'],reason:'لدعم الوجود والحقوق والقياس.'}),requirement('LEASE','سجل وعقود الإيجارات',{when:['إيجارات'],reason:'لدعم أصول حق الاستخدام والتزامات الإيجار.'}),requirement('DEBT','عقود القروض والتسهيلات',{when:['قروض وتمويل'],reason:'لدعم الاكتمال والتصنيف والقياس.'}),requirement('TAX','إقرارات وتسويات الضرائب والزكاة',{when:['ضرائب وزكاة'],reason:'لدعم أرصدة الضرائب والزكاة.'})],sections:['cover','basis-of-preparation','adjustment-summary','statement-of-financial-position','traceability-appendix']},
'full-financial-statements':{id:'full-financial-statements',title:'القوائم المالية الكاملة',aliases:['قوائم مالية','قوائم كاملة','قوائم مالية كاملة','financial statements'],engagementType:'preparation',minimumInputs:[requirement('TB','ميزان المراجعة النهائي',{priority:'critical',documentTypes:['trial-balance']}),requirement('COA','دليل الحسابات وربط الحسابات',{priority:'critical',documentTypes:['chart-of-accounts']}),requirement('PYFS','القوائم أو المقارنات للفترة السابقة',{priority:'high',documentTypes:['financial-statements']})],conditionalInputs:[],sections:['cover','basis-of-preparation','statement-of-financial-position','profit-or-loss','cash-flows','changes-in-equity','notes','adjustment-summary','traceability-appendix']},
'audit-report':{id:'audit-report',title:'تقرير مراجعة مالية',aliases:['تقرير مراجعة','تقرير مراقب حسابات','audit report','مراجعة القوائم'],engagementType:'audit',minimumInputs:[requirement('FS','مجموعة القوائم المالية محل المراجعة',{priority:'critical',documentTypes:['financial-statements']}),requirement('TB','ميزان المراجعة النهائي وربطه بالقوائم',{priority:'critical',documentTypes:['trial-balance']}),requirement('GL','الأستاذ العام وقيود الفترة',{priority:'critical',documentTypes:['general-ledger','journal']})],conditionalInputs:[],sections:['cover','opinion','basis-for-opinion','materiality','scope','key-audit-matters','going-concern','other-information','responsibilities','council-summary','evidence-coverage','adjustments','traceability-appendix']},
'management-letter':{id:'management-letter',title:'خطاب الإدارة ونقاط الرقابة',aliases:['management letter','خطاب ادارة','خطاب الإدارة','تقرير رقابة داخلية'],engagementType:'internal-control',minimumInputs:[requirement('CONTROL','وصف العمليات والضوابط الرئيسية',{priority:'critical'})],conditionalInputs:[],sections:['cover','executive-summary','control-findings','recommendations','management-responses','action-plan']},
'inventory-review':{id:'inventory-review',title:'مراجعة المخزون',aliases:['مخزون','مراجعة مخزون','inventory review'],engagementType:'agreed-procedures',minimumInputs:[requirement('INVLIST','كشف تفصيلي بالمخزون',{priority:'critical'}),requirement('COUNT','محاضر ونتائج الجرد',{priority:'critical'}),requirement('COST','مستندات التكلفة والمشتريات',{priority:'high'})],conditionalInputs:[],sections:['cover','scope','inventory-analysis','exceptions','adjustments','conclusion']}
});
function normalize(text=''){return String(text).trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[\u064B-\u065F\u0670]/g,'').replace(/\s+/g,' ')}
export function resolveReportIntent(input=''){const value=normalize(input);if(!value)return null;const scored=Object.values(REPORT_RECIPES).map(recipe=>{const aliases=[recipe.title,...recipe.aliases].map(normalize),exact=aliases.some(a=>a===value),contained=aliases.filter(a=>value.includes(a)||a.includes(value)).length;return{recipe,score:exact?1000:contained*10}}).sort((a,b)=>b.score-a.score);return scored[0]?.score>0?scored[0].recipe:null}
export function evaluateRecipeRequirements(recipeOrId,{categories=[],documentTypes=[],satisfiedRequirementIds=[]}={}){const recipe=typeof recipeOrId==='string'?REPORT_RECIPES[recipeOrId]:recipeOrId;if(!recipe)throw new RangeError('Unknown report recipe');const categorySet=new Set(categories),docSet=new Set(documentTypes),satisfied=new Set(satisfiedRequirementIds),all=[...recipe.minimumInputs];for(const item of recipe.conditionalInputs??[])if(!item.when||item.when.some(c=>categorySet.has(c)))all.push(item);return all.map(item=>({...item,status:satisfied.has(item.id)||(item.documentTypes??[]).some(t=>docSet.has(t))?'satisfied':'required'}))}
export function buildReportPlan(input,context={}){const recipe=typeof input==='string'&&REPORT_RECIPES[input]?REPORT_RECIPES[input]:resolveReportIntent(input);if(!recipe)return{understood:false,input,suggestions:Object.values(REPORT_RECIPES).map(i=>({id:i.id,title:i.title}))};const requirements=evaluateRecipeRequirements(recipe,context),required=requirements.filter(i=>i.status==='required');return{understood:true,recipe,requirements,required,readyForBuild:required.length===0,nextRequirement:required[0]??null}}
