/** KOSIF V5 — IndexedDB restore points inspired by the supplied dashboard safety layer. */
const DB_NAME='kosif-v5-safety';const DB_VERSION=1;const STORE='restore-points';const MAX_POINTS=8;
function openDb(){return new Promise((resolve,reject)=>{if(!globalThis.indexedDB)return reject(new Error('IndexedDB غير متاح في هذا المتصفح'));const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('createdAt','createdAt')}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('تعذر فتح مخزن نقاط الاستعادة'))})}
function requestResult(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('تم إلغاء معاملة التخزين'))})}
export function restorePointId(now=new Date()){return`RST-${now.toISOString().replace(/[-:.TZ]/g,'').slice(0,14)}`}
export async function createRestorePoint(snapshot,{label='نقطة استعادة يدوية',reason='manual'}={}){const db=await openDb();try{const point={id:restorePointId(),createdAt:new Date().toISOString(),label:String(label),reason:String(reason),snapshot:structuredClone(snapshot)};const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);s.put(point);await txDone(tx);const rows=await listRestorePoints();for(const extra of rows.slice(MAX_POINTS))await deleteRestorePoint(extra.id);return point}finally{db.close()}}
export async function listRestorePoints(){const db=await openDb();try{const tx=db.transaction(STORE,'readonly'),rows=await requestResult(tx.objectStore(STORE).getAll());await txDone(tx);return(rows||[]).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}finally{db.close()}}
export async function getRestorePoint(id){const db=await openDb();try{const tx=db.transaction(STORE,'readonly'),row=await requestResult(tx.objectStore(STORE).get(String(id)));await txDone(tx);return row||null}finally{db.close()}}
export async function deleteRestorePoint(id){const db=await openDb();try{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(String(id));await txDone(tx);return true}finally{db.close()}}
