/** KOSIF V5 — continuous evidence -> council -> request -> evidence loop orchestration. */
import{createEvidenceRequestsFromCouncilRound,refreshEvidenceRequests,evidenceRequestMetrics}from'./evidence-requests.js';
import{deriveEngagementStage,reportReadiness}from'./engagement-machine.js';
function nextRoundId(rounds=[]){const max=rounds.reduce((h,i)=>{const m=String(i.id??'').match(/^RND-(\d+)$/);return m?Math.max(h,Number(m[1])):h},0);return`RND-${String(max+1).padStart(3,'0')}`}
function nextEvidenceId(evidence=[]){const max=evidence.reduce((h,i)=>{const m=String(i.id??'').match(/^EVD-(\d+)$/);return m?Math.max(h,Number(m[1])):h},0);return`EVD-${String(max+1).padStart(4,'0')}`}
export function recordCouncilRound(engagement,inputRound={},{recordedAt=new Date().toISOString()}={}){const next=structuredClone(engagement),previous=next.councilRounds.at(-1)??null,round={...structuredClone(inputRound),id:inputRound.id??nextRoundId(next.councilRounds),number:next.councilRounds.length+1,label:inputRound.label??`Council Round ${next.councilRounds.length+1}`,status:'completed',recordedAt,previousRoundId:previous?.id??null,evidenceIds:inputRound.evidenceIds??next.evidence.filter(i=>['received','reviewed','sufficient'].includes(i.reviewStatus)).map(i=>i.id),issueIds:inputRound.issueIds??next.issues.filter(i=>i.status!=='closed').map(i=>i.id)};next.councilRounds.push(round);const req=createEvidenceRequestsFromCouncilRound(round,next.requests,{createdAt:recordedAt});next.requests=req.requests;next.evidence=next.evidence.map(i=>round.evidenceIds.includes(i.id)&&i.reviewStatus==='received'?{...i,reviewStatus:'reviewed',reviewedInRoundId:round.id}:i);next.requests=refreshEvidenceRequests(next.requests,next.evidence,{updatedAt:recordedAt});next.stage=deriveEngagementStage(next);next.updatedAt=recordedAt;return{engagement:next,round,createdRequests:req.created,deduplicatedRequests:req.deduplicated}}
export function ingestEvidenceBatch(engagement,items=[],{receivedAt=new Date().toISOString()}={}){const next=structuredClone(engagement),created=[];for(const raw of items){const item={id:raw.id??nextEvidenceId([...next.evidence,...created]),title:raw.title??raw.fileName??'دليل مراجعة',documentIds:[...new Set(raw.documentIds??[])],requestIds:[...new Set(raw.requestIds??[])],issueIds:[...new Set(raw.issueIds??[])],criteriaSatisfied:[...new Set(raw.criteriaSatisfied??[])],sourceType:raw.sourceType??'unknown',reviewStatus:raw.reviewStatus??'received',receivedAt};created.push(item)}next.evidence.push(...created);next.requests=refreshEvidenceRequests(next.requests,next.evidence,{updatedAt:receivedAt});next.stage=deriveEngagementStage(next);next.updatedAt=receivedAt;return{engagement:next,evidence:created}}
export function buildCouncilDelta(previousRound=null,currentRound=null,engagement={}){if(!currentRound)return null;if(!previousRound)return{initial:true,evidenceAdded:currentRound.evidenceIds?.length??0,issuesConsidered:currentRound.issueIds?.length??0,requestsOpen:evidenceRequestMetrics(engagement.requests).open};const pe=new Set(previousRound.evidenceIds??[]),pi=new Set(previousRound.issueIds??[]),ce=new Set(currentRound.evidenceIds??[]),ci=new Set(currentRound.issueIds??[]);return{initial:false,evidenceAdded:[...ce].filter(id=>!pe.has(id)),evidenceRemoved:[...pe].filter(id=>!ce.has(id)),issuesAdded:[...ci].filter(id=>!pi.has(id)),issuesClosedOrRemoved:[...pi].filter(id=>!ci.has(id)),requests:evidenceRequestMetrics(engagement.requests)}}
export function reviewLoopStatus(engagement={}){const latest=engagement.councilRounds?.at(-1)??null,previous=engagement.councilRounds?.at(-2)??null,requestMetrics=evidenceRequestMetrics(engagement.requests??[]),readiness=reportReadiness(engagement);return{stage:deriveEngagementStage(engagement),round:latest?.number??0,requestMetrics,readiness,delta:buildCouncilDelta(previous,latest,engagement),shouldConveneAgain:Boolean((engagement.evidence??[]).some(i=>i.reviewStatus==='received')),canBuildReport:readiness.ready}}
