/** KOSIF V5 — deterministic tabular/Excel intake before AI analysis. */
import { parseMoneyMinor, validateTrialBalance } from '../engine.js';

const MAX_BROWSER_ROWS=100000;
const SHEETJS_URL='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';
const ALIASES=Object.freeze({
  code:['accountcode','acccode','glcode','accountnumber','accountno','code','كودالحساب','رمزالحساب','رقمالحساب'],
  name:['accountname','accountdescription','description','name','اسمحساب','اسمالحساب','بيانالحساب','الوصف','البيان'],
  debit:['debit','debitbalance','debitamount','dr','مدين','رصيدمدين','اجماليمدين','إجماليمدين'],
  credit:['credit','creditbalance','creditamount','cr','دائن','رصيددائن','اجماليدائن','إجماليدائن']
});
function normalizeHeader(value=''){return String(value).trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[^a-z0-9\u0600-\u06ff]+/g,'')}
function headersFromRecords(records=[]){const set=new Set;for(const record of records.slice(0,20))if(record&&typeof record==='object'&&!Array.isArray(record))for(const key of Object.keys(record))set.add(key);return[...set]}
function bestAlias(header,field){const normalized=normalizeHeader(header),aliases=ALIASES[field];if(aliases.includes(normalized))return 100;let best=0;for(const alias of aliases){if(normalized.startsWith(alias)||normalized.endsWith(alias))best=Math.max(best,70);else if(alias.length>=4&&normalized.includes(alias))best=Math.max(best,50)}return best}
export function detectTrialBalanceColumns(headers=[]){const available=[...new Set(headers.map(String))],mapping={},used=new Set,detail={};for(const field of ['code','name','debit','credit']){let best=null;for(const header of available){if(used.has(header))continue;const score=bestAlias(header,field);if(score&&(!best||score>best.score))best={header,score}}if(best){mapping[field]=best.header;detail[field]=best.score;used.add(best.header)}}const hasAmounts=Boolean(mapping.debit&&mapping.credit),hasIdentity=Boolean(mapping.name||mapping.code),requiredMatched=[mapping.name,mapping.debit,mapping.credit].filter(Boolean).length;const score=(hasAmounts?50:0)+(hasIdentity?20:0)+requiredMatched*8+(mapping.code?6:0);return{recognized:hasAmounts&&hasIdentity,mapping,score:Math.min(100,score),confidence:score>=90?'high':score>=70?'medium':'low',detail,headers:available}}
function normalizeNegativeText(text){const trimmed=String(text??'').trim();if(/^\(.*\)$/.test(trimmed))return`-${trimmed.slice(1,-1)}`;return trimmed}
function moneyCell(value,{row,column}={}){if(value==null||value==='')return 0n;if(typeof value==='number'){if(!Number.isFinite(value)||Math.abs(value)>Number.MAX_SAFE_INTEGER)throw new RangeError(`Unsafe numeric value at row ${row}, ${column}; import the amount as text/CSV to preserve precision.`);return parseMoneyMinor(String(value))}if(typeof value==='bigint')return parseMoneyMinor(value.toString());const text=normalizeNegativeText(value).replace(/^[-–—]$/,'0');return parseMoneyMinor(text||'0')}
export function recordsToTrialBalance(records=[]){if(!Array.isArray(records))throw new TypeError('records must be an array');const detection=detectTrialBalanceColumns(headersFromRecords(records));if(!detection.recognized)return{recognized:false,rows:[],detection,warnings:['لم يتم التعرف بثقة على أعمدة الحساب والمدين والدائن.'],skipped:records.length};const {mapping}=detection,rows=[],warnings=[];let skipped=0;for(let index=0;index<records.length;index++){const record=records[index]||{},code=String(mapping.code?record[mapping.code]??'':'').trim(),name=String(mapping.name?record[mapping.name]??'':'').trim(),debitRaw=record[mapping.debit],creditRaw=record[mapping.credit];if(!code&&!name&&(debitRaw==null||debitRaw==='')&&(creditRaw==null||creditRaw==='')){skipped++;continue}try{rows.push({id:`TB-${String(rows.length+1).padStart(6,'0')}`,code,name,debit:moneyCell(debitRaw,{row:index+2,column:mapping.debit}),credit:moneyCell(creditRaw,{row:index+2,column:mapping.credit}),source:'spreadsheet-intake'})}catch(error){error.row=index+2;throw error}}const validation=validateTrialBalance(rows);if(!validation.balanced)warnings.push(`ميزان المراجعة غير متزن بفارق ${validation.imbalance.toString()} وحدة صغرى.`);if(validation.rowIssues.length)warnings.push(`${validation.rowIssues.length} ملاحظة جودة على الصفوف.`);return{recognized:true,rows,detection,warnings,skipped,validation:{balanced:validation.balanced,imbalance:validation.imbalance,totalDebit:validation.totalDebit,totalCredit:validation.totalCredit,accounts:validation.metrics.accounts,rowIssueCount:validation.rowIssues.length}}}
function detectDelimiter(text=''){const line=String(text).split(/\r?\n/,1)[0]||'',scores=[[',',(line.match(/,/g)||[]).length],[';',(line.match(/;/g)||[]).length],['\t',(line.match(/\t/g)||[]).length]];scores.sort((a,b)=>b[1]-a[1]);return scores[0][1]?scores[0][0]:','}
export function parseDelimitedRecords(text='',delimiter=detectDelimiter(text)){const rows=[];let row=[],cell='',quoted=false;const input=String(text).replace(/^\uFEFF/,'');for(let i=0;i<input.length;i++){const ch=input[i];if(ch==='"'){if(quoted&&input[i+1]==='"'){cell+='"';i++}else quoted=!quoted;continue}if(ch===delimiter&&!quoted){row.push(cell);cell='';continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&input[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[];continue}cell+=ch}row.push(cell);if(row.some(v=>String(v).trim()!==''))rows.push(row);if(!rows.length)return[];const headers=rows.shift().map((h,i)=>String(h).trim()||`column_${i+1}`);return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??''])))}
export function parseJsonRecords(text=''){const value=JSON.parse(String(text));const records=Array.isArray(value)?value:Array.isArray(value?.rows)?value.rows:Array.isArray(value?.data)?value.data:null;if(!records)throw new TypeError('JSON trial balance must be an array or contain rows/data array');return records}
function extension(name=''){const clean=String(name).toLowerCase().split(/[?#]/)[0],dot=clean.lastIndexOf('.');return dot>=0?clean.slice(dot+1):''}
export function isSupportedTabularFile(file={}){return['csv','tsv','txt','json','xlsx','xls','xlsm'].includes(extension(file.name||''))}
export async function ensureSheetJs({documentRef=globalThis.document,timeoutMs=15000}={}){if(globalThis.XLSX?.read)return globalThis.XLSX;if(!documentRef?.createElement)throw new Error('SheetJS is unavailable outside a browser context');const existing=documentRef.querySelector?.('script[data-kosif-xlsx]');if(existing){await new Promise((resolve,reject)=>{if(globalThis.XLSX?.read)return resolve();const timer=setTimeout(()=>reject(new Error('SheetJS load timeout')),timeoutMs);existing.addEventListener('load',()=>{clearTimeout(timer);resolve()},{once:true});existing.addEventListener('error',()=>{clearTimeout(timer);reject(new Error('SheetJS failed to load'))},{once:true})});if(globalThis.XLSX?.read)return globalThis.XLSX}const script=documentRef.createElement('script');script.src=SHEETJS_URL;script.async=true;script.dataset.kosifXlsx='true';script.crossOrigin='anonymous';await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('SheetJS load timeout')),timeoutMs);script.onload=()=>{clearTimeout(timer);resolve()};script.onerror=()=>{clearTimeout(timer);reject(new Error('SheetJS failed to load'))};(documentRef.head||documentRef.documentElement).append(script)});if(!globalThis.XLSX?.read)throw new Error('SheetJS loaded without XLSX API');return globalThis.XLSX}
function chooseWorkbookRecords(workbook,XLSX){let best=null;for(const sheetName of workbook.SheetNames||[]){const sheet=workbook.Sheets[sheetName];if(!sheet)continue;const records=XLSX.utils.sheet_to_json(sheet,{defval:'',raw:true});if(!records.length)continue;const detection=detectTrialBalanceColumns(headersFromRecords(records));const candidate={sheetName,records,detection};if(!best||candidate.detection.score>best.detection.score)best=candidate}return best}
export async function parseTrialBalanceFile(file,{sheetJsLoader=ensureSheetJs}={}){if(!(file instanceof Blob))throw new TypeError('File/Blob is required');const ext=extension(file.name||'');if(!isSupportedTabularFile(file))return{supported:false,recognized:false,rows:[],warnings:['نوع الملف ليس من تنسيقات الجدول المدعومة مباشرة.']};if(['csv','tsv','txt'].includes(ext)){const records=parseDelimitedRecords(await file.text(),ext==='tsv'?'\t':undefined);return{supported:true,format:ext,...recordsToTrialBalance(records)}}if(ext==='json'){return{supported:true,format:'json',...recordsToTrialBalance(parseJsonRecords(await file.text()))}}const XLSX=await sheetJsLoader(),buffer=await file.arrayBuffer(),workbook=XLSX.read(buffer,{type:'array',cellDates:false}),best=chooseWorkbookRecords(workbook,XLSX);if(!best)return{supported:true,format:ext,recognized:false,rows:[],warnings:['لم يتم العثور على ورقة بيانات قابلة للقراءة في المصنف.']};if(best.records.length>MAX_BROWSER_ROWS)throw new RangeError(`Spreadsheet exceeds browser intake limit (${MAX_BROWSER_ROWS} rows)`);return{supported:true,format:ext,sheetName:best.sheetName,...recordsToTrialBalance(best.records)}}
export{MAX_BROWSER_ROWS,SHEETJS_URL,normalizeHeader,moneyCell};
