/** KOSIF V5 — account-level lineage for SFP/P&L comparison rows. */
import { validateTrialBalance } from '../engine.js';
import { STATEMENT_LAYOUT } from '../analytics.js';
import { buildAdjustedTrialBalance } from './adjustment-ledger.js';
import { buildStatementComparison, sectionForRow } from './statement-comparison.js';

const sectionSide=new Map(STATEMENT_LAYOUT.map(item=>[item.section,item.side]));
const key=v=>String(v??'');
function indexRows(rows=[]){const map=new Map;for(const row of validateTrialBalance(rows).rows){if(row.id)map.set(key(row.id),row);if(row.code&&!map.has(key(row.code)))map.set(key(row.code),row)}return map}
function naturalAmount(row){if(!row)return 0n;const section=sectionForRow(row);if(!section)return 0n;return sectionSide.get(section)==='credit'?-row.net:row.net}
function contribution(row,line){if(!row)return 0n;const section=sectionForRow(row);if(!section||!line.sections.includes(section))return 0n;const natural=naturalAmount(row);return line.id==='profit'&&section==='expenses'?-natural:natural}
function acceptedAdjustmentsForAccount(adjustments=[],account={}){const ids=new Set([key(account.id),key(account.code)].filter(Boolean));return adjustments.filter(a=>a.status==='accepted'&&(a.lines||[]).some(line=>ids.has(key(line.accountId))||ids.has(key(line.code))))}
export function buildStatementLineage(originalRows=[],adjustments=[],lineId){const comparison=buildStatementComparison(originalRows,adjustments),line=comparison.rows.find(row=>row.id===lineId);if(!line)throw new RangeError(`Unknown statement line: ${lineId}`);const originalMap=indexRows(originalRows),adjustedTB=buildAdjustedTrialBalance(originalRows,adjustments),adjustedMap=indexRows(adjustedTB.rows);const accounts=line.accountIds.map(id=>{const original=originalMap.get(id)||null,adjusted=adjustedMap.get(id)||null,row=adjusted||original,linked=acceptedAdjustmentsForAccount(adjustments,row||{id});const originalContribution=contribution(original,line),adjustedContribution=contribution(adjusted,line);return{id:key(row?.id||id),code:key(row?.code||''),name:row?.name||'حساب غير مسمى',category:row?.category||null,section:row?sectionForRow(row):null,standards:[...(row?.standards||[])],assertions:[...(row?.assertions||[])],originalDebit:original?.debit||0n,originalCredit:original?.credit||0n,adjustedDebit:adjusted?.debit||0n,adjustedCredit:adjusted?.credit||0n,originalContribution,adjustedContribution,difference:adjustedContribution-originalContribution,adjustmentIds:linked.map(a=>a.id),issueIds:[...new Set(linked.map(a=>a.issueId).filter(Boolean))],evidenceIds:[...new Set(linked.flatMap(a=>a.evidenceIds||[]))],councilRoundIds:[...new Set(linked.map(a=>a.councilRoundId).filter(Boolean))],source:original?.source||adjusted?.source||null}});const originalSum=accounts.reduce((sum,a)=>sum+a.originalContribution,0n),adjustedSum=accounts.reduce((sum,a)=>sum+a.adjustedContribution,0n);return{line:{...line},accounts,adjustments:adjustments.filter(a=>line.adjustmentIds.includes(a.id)).map(a=>structuredClone(a)),checks:{originalReconciles:originalSum===line.original,adjustedReconciles:adjustedSum===line.adjusted,originalSum,adjustedSum,originalDifference:originalSum-line.original,adjustedDifference:adjustedSum-line.adjusted},metrics:{accounts:accounts.length,changedAccounts:accounts.filter(a=>a.difference!==0n).length,adjustments:line.adjustmentIds.length,evidence:[...new Set(accounts.flatMap(a=>a.evidenceIds))].length,issues:[...new Set(accounts.flatMap(a=>a.issueIds))].length}}}
export function statementLineageSummary(lineage={}){return{lineId:lineage.line?.id||null,label:lineage.line?.label||null,accounts:lineage.metrics?.accounts||0,changedAccounts:lineage.metrics?.changedAccounts||0,adjustments:lineage.metrics?.adjustments||0,originalReconciles:Boolean(lineage.checks?.originalReconciles),adjustedReconciles:Boolean(lineage.checks?.adjustedReconciles)}}
