import test from 'node:test';
import assert from 'node:assert/strict';
import { createEngagement } from '../v5/engagement-machine.js';
import { normalizeAssertion, issueAssertionCoverage, engagementAssertionCoverage, compareCouncilRounds } from '../v5/audit-coverage.js';

test('assertion normalization handles audit aliases without inventing unknown assertions',()=>{assert.equal(normalizeAssertion('Existence'),'existence');assert.equal(normalizeAssertion('التقييم'),'valuation');assert.equal(normalizeAssertion('Cut-off'),'cutoff');assert.equal(normalizeAssertion('something else'),null)});

test('coverage denominator contains declared assertions only and requires reviewed evidence',()=>{const e=createEngagement({id:'ENG-C'});e.issues.push({id:'ISS-1',title:'مخزون',status:'open',riskIds:['R-1'],assertions:['Existence','Valuation']});e.evidence.push({id:'EVD-1',riskIds:['R-1'],reviewStatus:'reviewed',claim:{assertion:'Existence'}},{id:'EVD-2',riskIds:['R-1'],reviewStatus:'unreviewed',claim:{assertion:'Valuation'}},{id:'EVD-X',riskIds:['R-1'],reviewStatus:'reviewed',claim:{assertion:'Completeness'}});const c=issueAssertionCoverage(e,'ISS-1');assert.equal(c.total,2);assert.equal(c.covered,1);assert.equal(c.coveragePercent,50);assert.equal(c.rows.find(r=>r.assertion==='existence').status,'covered');assert.equal(c.rows.find(r=>r.assertion==='valuation').status,'unreviewed')});

test('an open governed request is displayed as requested, never as covered evidence',()=>{const e=createEngagement({id:'ENG-C'});e.issues.push({id:'ISS-1',title:'عملاء',status:'open',riskIds:['R-1'],assertions:['Valuation']});e.requests.push({id:'REQ-1',status:'requested',riskIds:['R-1']});const c=issueAssertionCoverage(e,'ISS-1');assert.equal(c.rows[0].status,'requested');assert.equal(c.covered,0)});

test('issues without declared assertions are excluded from aggregate percentage',()=>{const e=createEngagement({id:'ENG-C'});e.issues.push({id:'ISS-1',title:'Known',status:'open',riskIds:['R-1'],assertions:['Existence']},{id:'ISS-2',title:'Unknown assertions',status:'open',riskIds:['R-2'],assertions:[]});e.evidence.push({id:'EVD-1',riskIds:['R-1'],reviewStatus:'reviewed',claim:{assertion:'Existence'}});const c=engagementAssertionCoverage(e);assert.equal(c.coveragePercent,100);assert.deepEqual(c.issuesWithoutDeclaredAssertions,['ISS-2'])});

test('council delta reports source movement and seat stance changes between immutable rounds',()=>{const previous={id:'RND-1',number:1,evidenceIds:['E1'],issueIds:['I1','I2'],positions:[{seatId:'isa',title:'ISA',stance:'caution'},{seatId:'quality',title:'Quality',stance:'clear'}]},current={id:'RND-2',number:2,evidenceIds:['E1','E2'],issueIds:['I2','I3'],positions:[{seatId:'isa',title:'ISA',stance:'clear'},{seatId:'quality',title:'Quality',stance:'clear'}]};const e=createEngagement({id:'ENG-C'});e.requests=[{id:'REQ-1',status:'satisfied'},{id:'REQ-2',status:'requested'}];const d=compareCouncilRounds(previous,current,e);assert.deepEqual(d.evidenceAdded,['E2']);assert.deepEqual(d.issuesAdded,['I3']);assert.deepEqual(d.issuesClosedOrRemoved,['I1']);assert.deepEqual(d.seatChanges,[{seatId:'isa',title:'ISA',before:'caution',after:'clear'}]);assert.deepEqual(d.openRequests,['REQ-2']);assert.deepEqual(d.satisfiedRequests,['REQ-1'])});
