import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeDashboardText, dashboardMetrics, dataQualityReport, accountConcentration, buildSearchIndex, searchWorkspace } from '../v5/dashboard-capabilities.js';

test('dashboard normalization supports Arabic variants and Arabic-Indic digits',()=>{assert.equal(normalizeDashboardText('  إيرادات ٢٠٢٦ '),'ايرادات 2026');assert.equal(normalizeDashboardText('الأدلّة'),'الادله')});

test('dashboard metrics count active audit objects without turning closed items into alerts',()=>{const engagement={documents:[{id:'D1',type:'bank-statement'}],evidence:[{id:'E1',reviewStatus:'reviewed',documentIds:['D1']},{id:'E2',reviewStatus:'received',documentIds:['D1']}],requests:[{status:'requested'},{status:'satisfied'}],issues:[{status:'open',severity:'high',assertions:['existence']},{status:'resolved',severity:'critical',assertions:['valuation']}],councilRounds:[{number:1,evidenceIds:['E1'],issueIds:['I1']}],adjustments:[{status:'accepted',lines:[{side:'debit',amountMinor:100n},{side:'credit',amountMinor:100n}]}],reports:[]};const m=dashboardMetrics({engagement});assert.equal(m.documents,1);assert.equal(m.evidenceReviewPercent,50);assert.equal(m.openRequests,1);assert.equal(m.openIssues,1);assert.equal(m.highIssues,1);assert.equal(m.acceptedAdjustments,1);assert.equal(m.adjustmentImpact,100n)});

test('data quality score penalizes broken source lineage, missing criteria and unbalanced adjustments',()=>{const engagement={documents:[{id:'D1',sha256:'x',type:'trial-balance'},{id:'D2',sha256:'x',type:'trial-balance'}],evidence:[{id:'E1',reviewStatus:'received',documentIds:['MISSING']}],issues:[{id:'I1',status:'open',severity:'high',assertions:[]}],requests:[{id:'R1',status:'requested',acceptanceCriteria:[]}],adjustments:[{id:'A1',lines:[{side:'debit',amountMinor:10n},{side:'credit',amountMinor:9n}]}],reports:[]};const q=dataQualityReport(engagement,{rows:[{}]},null);assert.ok(q.score<70);assert.equal(q.counts.duplicateDocs,1);assert.equal(q.counts.missingEvidenceSource,1);assert.equal(q.counts.unbalanced,1);assert.equal(q.counts.requestCriteria,1)});

test('account concentration is deterministic and reports top share without floats in accountable state',()=>{const analysis={rows:[{id:'A',name:'أ',debit:700n,credit:0n},{id:'B',name:'ب',debit:200n,credit:0n},{id:'C',name:'ج',debit:100n,credit:0n}]};const c=accountConcentration(analysis,1);assert.equal(c.total,1000n);assert.equal(c.top[0].amount,700n);assert.equal(c.topShare,70)});

test('global search indexes audit objects and Arabic-normalized queries',()=>{const engagement={documents:[{id:'DOC-1',name:'كشف البنك',type:'bank-statement'}],evidence:[],issues:[{id:'ISS-1',title:'إيرادات غير مؤيدة',status:'open',severity:'high',standards:['IFRS 15']}],requests:[],adjustments:[],reports:[],councilRounds:[]};const index=buildSearchIndex(engagement,{rows:[{id:'ACC-1',code:'1001',name:'النقدية',category:'نقدية وبنوك'}]});assert.equal(searchWorkspace('ايرادات',index)[0].id,'ISS-1');assert.equal(searchWorkspace('النقديه',index)[0].id,'ACC-1');assert.equal(searchWorkspace('كشف البنك',index)[0].id,'DOC-1')});
