import test from 'node:test';
import assert from 'node:assert/strict';
import { createEngagement } from '../v5/engagement-machine.js';
import { disclosureCandidates, recordDisclosureReview, disclosureStatus } from '../v5/disclosure-engine.js';
import { completionRequirements, recordCompletionDecision } from '../v5/completion-engine.js';

const rows=[{id:'A1',category:'مخزون',standards:['IAS 2']},{id:'A2',category:'نقدية وبنوك',standards:['IFRS 9']}];

test('full statements produce disclosure candidates only from deterministic triggers plus base policies',()=>{const e=createEngagement({id:'ENG-D',engagementType:'preparation'}),c=disclosureCandidates({rows,engagement:e,recipeId:'full-financial-statements'}),ids=c.map(x=>x.topicId);assert.ok(ids.includes('BASIS_POLICIES'));assert.ok(ids.includes('INVENTORIES'));assert.ok(ids.includes('FINANCIAL_INSTRUMENTS'));assert.equal(ids.includes('LEASES'),false);assert.equal(disclosureCandidates({rows,engagement:e,recipeId:'statement-of-financial-position'}).length,0)});

test('disclosure review is append-only, human-only and enforces applicable -> prepared -> reviewed sequence',()=>{let e=createEngagement({id:'ENG-D',engagementType:'preparation'});assert.throws(()=>recordDisclosureReview(e,{topicId:'INVENTORIES',status:'applicable',actor:'AI',actorType:'ai',rationale:'x'}),/human/);assert.throws(()=>recordDisclosureReview(e,{topicId:'INVENTORIES',status:'prepared',actor:'Reviewer',actorType:'human',rationale:'x'}),/applicable/);let r=recordDisclosureReview(e,{topicId:'INVENTORIES',status:'applicable',actor:'Reviewer',actorType:'human',rationale:'يوجد مخزون'});e=r.engagement;r=recordDisclosureReview(e,{topicId:'INVENTORIES',status:'prepared',actor:'Reviewer',actorType:'human',rationale:'تم إعداد الإيضاح'});e=r.engagement;r=recordDisclosureReview(e,{topicId:'INVENTORIES',status:'reviewed',actor:'Manager',actorType:'human',rationale:'تمت المراجعة'});e=r.engagement;assert.equal(e.disclosureReviews.length,3);assert.equal(e.disclosureReviews[2].previousReviewId,e.disclosureReviews[1].id);assert.equal(disclosureCandidates({rows,engagement:e,recipeId:'full-financial-statements'}).find(x=>x.topicId==='INVENTORIES').status,'reviewed')});

test('not-applicable requires a human rationale and resolves that disclosure candidate without deleting it',()=>{let e=createEngagement({id:'ENG-D',engagementType:'preparation'});e=recordDisclosureReview(e,{topicId:'FINANCIAL_INSTRUMENTS',status:'not-applicable',actor:'Reviewer',actorType:'human',rationale:'النطاق لا يتطلب هذا الموضوع في المخرج المحدد'}).engagement;const c=disclosureCandidates({rows,engagement:e,recipeId:'full-financial-statements'}).find(x=>x.topicId==='FINANCIAL_INSTRUMENTS');assert.equal(c.status,'not-applicable');assert.equal(c.review.actor,'Reviewer')});

test('full financial statements completion gate stays blocked until detailed disclosure candidates are resolved',()=>{let e=createEngagement({id:'ENG-D',engagementType:'preparation'}),ds=disclosureStatus({rows,engagement:e,recipeId:'full-financial-statements'});let gate=completionRequirements(e,{recipeId:'full-financial-statements',traceabilityMetrics:{isolated:[]},disclosureStatus:ds}).find(x=>x.id==='DISCLOSURE_REVIEW');assert.equal(gate.status,'blocked');assert.equal(gate.prerequisiteMissing,true);for(const candidate of ds.candidates)e=recordDisclosureReview(e,{topicId:candidate.topicId,status:'not-applicable',actor:'Reviewer',actorType:'human',rationale:'قرار انطباق موثق للاختبار'}).engagement;ds=disclosureStatus({rows,engagement:e,recipeId:'full-financial-statements'});assert.equal(ds.ready,true);gate=completionRequirements(e,{recipeId:'full-financial-statements',traceabilityMetrics:{isolated:[]},disclosureStatus:ds}).find(x=>x.id==='DISCLOSURE_REVIEW');assert.equal(gate.status,'pending');assert.equal(gate.prerequisiteMissing,undefined);e=recordCompletionDecision(e,{checkId:'DISCLOSURE_REVIEW',status:'satisfied',actor:'Manager',actorType:'human',rationale:'راجعت قائمة الإفصاحات التفصيلية'}).engagement;gate=completionRequirements(e,{recipeId:'full-financial-statements',traceabilityMetrics:{isolated:[]},disclosureStatus:ds}).find(x=>x.id==='DISCLOSURE_REVIEW');assert.equal(gate.status,'satisfied')});
