import test from 'node:test';
import assert from 'node:assert/strict';
import gateway from '../cloudflare/gateway-worker.js';
import { createDocumentIntelligenceClient } from '../v5/document-client.js';

async function hash(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function readerDb({engagementId='ENG-A',tokenHash,documentId='DOC-1'}={}){return{prepare(sql){return{args:[],bind(...args){this.args=args;return this},async first(){if(/SELECT access_token_hash FROM engagement_sessions/.test(sql)&&this.args[0]===engagementId)return{access_token_hash:tokenHash};if(/SELECT engagement_id, storage_key, mime_type, name FROM documents/.test(sql)&&this.args[0]===documentId)return{engagement_id:engagementId,storage_key:`${engagementId}/${documentId}/v1/test.pdf`,mime_type:'application/pdf',name:'test.pdf'};if(/SELECT document_id, model, response_id, analysis_json/.test(sql)&&this.args[0]===documentId)return{document_id:documentId,model:'gpt-5.6-terra',response_id:'resp-1',analysis_json:JSON.stringify({summary:'محلل',claims:[]}),created_at:'2026-09-10T00:00:00Z'};return null},async all(){if(/FROM documents WHERE engagement_id/.test(sql)&&this.args[0]===engagementId)return{results:[{id:documentId,engagement_id:engagementId,name:'test.pdf',mime_type:'application/pdf',size_bytes:6,sha256:'abc',document_type:'pdf-document',created_at:'2026-09-10T00:00:00Z'}]};return{results:[]}}}}}}
const request=(path,{token='',engagementId='ENG-A',method='GET'}={})=>new Request(`https://worker.test${path}`,{method,headers:{Origin:'https://app.test',...(engagementId?{'X-KOSIF-Engagement':engagementId}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}});

test('persisted document list is fail-closed without engagement bearer token',async()=>{const token='reader-secret',env={KOSIF_DB:readerDb({tokenHash:await hash(token)}),PERSISTENCE_ALLOWED_ORIGIN:'https://app.test'};const response=await gateway.fetch(request('/api/engagements/ENG-A/documents',{token:''}),env,{});assert.equal(response.status,401);assert.equal((await response.json()).error,'authorization_required')});

test('authorized engagement can list its documents but a different token cannot read document analysis',async()=>{const token='reader-secret',env={KOSIF_DB:readerDb({tokenHash:await hash(token)}),PERSISTENCE_ALLOWED_ORIGIN:'https://app.test'};let response=await gateway.fetch(request('/api/engagements/ENG-A/documents',{token}),env,{});assert.equal(response.status,200);assert.equal((await response.json()).documents[0].id,'DOC-1');response=await gateway.fetch(request('/api/documents/DOC-1/analysis',{token:'wrong'}),env,{});assert.equal(response.status,403);assert.equal((await response.json()).error,'invalid_engagement_token')});

test('document analysis rejects a claimed engagement that differs from the persisted owner',async()=>{const token='reader-secret',env={KOSIF_DB:readerDb({tokenHash:await hash(token)}),PERSISTENCE_ALLOWED_ORIGIN:'https://app.test'};const response=await gateway.fetch(request('/api/documents/DOC-1/analysis',{token,engagementId:'ENG-B'}),env,{});assert.equal(response.status,409);assert.equal((await response.json()).error,'engagement_id_mismatch')});

test('authorized document content streams from R2 with private no-store headers',async()=>{const token='reader-secret',env={KOSIF_DB:readerDb({tokenHash:await hash(token)}),KOSIF_DOCUMENTS:{async get(key){assert.equal(key,'ENG-A/DOC-1/v1/test.pdf');return{body:new Blob(['secret']),httpMetadata:{contentType:'application/pdf'}}}},PERSISTENCE_ALLOWED_ORIGIN:'https://app.test'};const response=await gateway.fetch(request('/api/documents/DOC-1/content',{token}),env,{});assert.equal(response.status,200);assert.equal(response.headers.get('Content-Type'),'application/pdf');assert.match(response.headers.get('Cache-Control')||'',/no-store/);assert.equal(await response.text(),'secret')});

test('protected document read preflight permits Authorization without exposing a public object URL',async()=>{const env={KOSIF_DB:readerDb({tokenHash:'x'}),PERSISTENCE_ALLOWED_ORIGIN:'https://app.test'};const response=await gateway.fetch(new Request('https://worker.test/api/documents/DOC-1/content',{method:'OPTIONS',headers:{Origin:'https://app.test','Access-Control-Request-Method':'GET','Access-Control-Request-Headers':'authorization,x-kosif-engagement'}}),env,{});assert.equal(response.status,204);assert.match(response.headers.get('Access-Control-Allow-Headers')||'',/Authorization/)});

test('document reader client sends bearer headers for list, analysis and content and never puts the token in URLs',async()=>{const calls=[];const fetchImpl=async(url,options={})=>{calls.push({url,options});if(url.endsWith('/content'))return new Response(new Blob(['x'],{type:'application/pdf'}),{status:200,headers:{'Content-Type':'application/pdf'}});return new Response(JSON.stringify(url.includes('/analysis')?{ok:true,analysis:{}}:{ok:true,documents:[]}),{status:200,headers:{'Content-Type':'application/json'}})};const client=createDocumentIntelligenceClient({baseUrl:'https://worker.test',fetchImpl,accessToken:'private-token'});await client.listDocuments('ENG-A');await client.getAnalysis('DOC-1',{engagementId:'ENG-A'});await client.getContent('DOC-1',{engagementId:'ENG-A'});for(const call of calls){assert.equal(call.options.headers.Authorization,'Bearer private-token');assert.equal(call.options.headers['X-KOSIF-Engagement'],'ENG-A');assert.equal(call.url.includes('private-token'),false)}});
