import test from 'node:test';
import assert from 'node:assert/strict';
import { createEngagement } from '../v5/engagement-machine.js';
import { equityReadiness, normalizeEquityMovement } from '../v5/equity-engine.js';
import { recordEquityVersion, latestEquityVersion } from '../v5/equity-workflow.js';
import { REPORT_RECIPES } from '../v5/report-recipes.js';
import { buildProfessionalReportModel } from '../v5/report-model.js';
import { attachDisclosureSection } from '../v5/report-disclosures.js';
import { reportSourceFingerprint, reportIsStale } from '../v5/report-source.js';
import { matchesDocument } from '../v5/report-intake.js';

function engagement(){const e=createEngagement({id:'ENG-EQ',entity:'شركة اختبار',engagementType:'preparation'});e.documents.push({id:'DOC-OPEN',name:'prior-equity.pdf',sha256:'a',version:1,status:'classified'},{id:'DOC-CLOSE',name:'closing-equity.pdf',sha256:'b',version:1,status:'classified'},{id:'DOC-MOVE',name:'equity-movements.xlsx',sha256:'c',version:1,status:'classified'});return e}
function input(){return{components:[{id:'EQC-CAP',label:'رأس المال',openingMinor:1000000n,closingMinor:1200000n,openingSourceIds:['DOC-OPEN'],closingSourceIds:['DOC-CLOSE']},{id:'EQC-RE',label:'الأرباح المبقاة',openingMinor:500000n,closingMinor:570000n,openingSourceIds:['DOC-OPEN'],closingSourceIds:['DOC-CLOSE']}],movements:[{id:'EQM-1',componentId:'EQC-CAP',label:'إصدار رأس مال',kind:'capital-issue',direction:'increase',amountMinor:200000n,sourceIds:['DOC-MOVE']},{id:'EQM-2',componentId:'EQC-RE',label:'ربح الفترة',kind:'profit-or-loss',direction:'increase',amountMinor:100000n,sourceIds:['DOC-MOVE']},{id:'EQM-3',componentId:'EQC-RE',label:'توزيعات',kind:'dividend',direction:'decrease',amountMinor:30000n,sourceIds:['DOC-MOVE']}]}}

test('equity engine keeps accountable amounts in integer minor units and validates movement contracts',()=>{const bad=input();bad.components[0].openingMinor='1.5';assert.equal(equityReadiness(bad).ready,false);assert.throws(()=>normalizeEquityMovement({componentId:'EQC-1',kind:'magic',direction:'increase',amountMinor:'100',sourceIds:['DOC-1']}),/kind/);assert.throws(()=>normalizeEquityMovement({componentId:'EQC-1',kind:'other',direction:'sideways',amountMinor:'100',sourceIds:['DOC-1']}),/direction/)});

test('each equity component reconciles independently and totals are exact',()=>{const r=equityReadiness(input());assert.equal(r.ready,true);assert.equal(r.statement.openingTotalMinor,1500000n);assert.equal(r.statement.movementTotalMinor,270000n);assert.equal(r.statement.closingTotalMinor,1770000n);assert.equal(r.statement.reconciliationDeltaMinor,0n);assert.ok(r.statement.components.every(c=>c.reconciled))});

test('offsetting component errors cannot hide behind a correct total equity balance',()=>{const data=input();data.components[0].closingMinor=1190000n;data.components[1].closingMinor=580000n;const r=equityReadiness(data);assert.equal(r.statement.closingTotalMinor,1770000n);assert.equal(r.statement.reconciliationDeltaMinor,0n);assert.equal(r.ready,false);assert.equal(r.statement.reconciled,false);assert.equal(r.statement.components.filter(c=>!c.reconciled).length,2)});

test('missing component or movement sources block readiness',()=>{let data=input();data.components[0].openingSourceIds=[];let r=equityReadiness(data);assert.equal(r.ready,false);assert.ok(r.blockers.some(b=>b.type==='unsupported-components'));data=input();data.movements[0].sourceIds=[];r=equityReadiness(data);assert.equal(r.ready,false);assert.ok(r.blockers.some(b=>b.type==='unsupported-movements'))});

test('equity approval is human-only, validates source ownership and appends immutable versions',()=>{const e=engagement();assert.throws(()=>recordEquityVersion(e,input(),{actor:'KOSIF',actorType:'ai',rationale:'auto'}),/human/);const unknown=input();unknown.movements=unknown.movements.map((m,i)=>i===0?{...m,sourceIds:['DOC-UNKNOWN']}:m);assert.throws(()=>recordEquityVersion(e,unknown,{actor:'Reviewer',actorType:'human',rationale:'reviewed'}),/Unknown equity source IDs/);const first=recordEquityVersion(e,input(),{actor:'Reviewer',actorType:'human',rationale:'تمت مطابقة حركة حقوق الملكية'},{at:'2026-09-10T10:00:00Z'});assert.equal(e.equityVersions,undefined);assert.equal(first.version.id,'EQV-001');const second=recordEquityVersion(first.engagement,input(),{actor:'Manager',actorType:'human',rationale:'مراجعة نهائية'},{at:'2026-09-10T11:00:00Z'});assert.equal(second.version.id,'EQV-002');assert.equal(second.version.previousVersionId,'EQV-001');assert.equal(latestEquityVersion(second.engagement).actor,'Manager')});

test('full financial report uses only an approved reconciled equity version',()=>{let e=engagement();let report=buildProfessionalReportModel({engagement:e,recipe:REPORT_RECIPES['full-financial-statements'],traceabilityMetrics:{nodes:1,edges:0,isolated:[]},documentMetrics:{documentsAnalyzed:0,claims:0,risks:0}});report=attachDisclosureSection(report,{rows:[],engagement:e});let section=report.sections.find(s=>s.id==='changes-in-equity');assert.equal(section.status,'unavailable');e=recordEquityVersion(e,input(),{actor:'Reviewer',actorType:'human',rationale:'مصادر متصالحة'}).engagement;report=buildProfessionalReportModel({engagement:e,recipe:REPORT_RECIPES['full-financial-statements'],traceabilityMetrics:{nodes:1,edges:0,isolated:[]},documentMetrics:{documentsAnalyzed:0,claims:0,risks:0}});report=attachDisclosureSection(report,{rows:[],engagement:e});section=report.sections.find(s=>s.id==='changes-in-equity');assert.equal(section.status,'human-required');assert.equal(section.equityVersionId,'EQV-001');assert.equal(section.facts.find(f=>f.label==='فرق التسوية').value,0n);assert.ok(section.sourceIds.includes('DOC-MOVE'))});

test('new equity version invalidates an older report source fingerprint',()=>{let e=engagement();const report={sourceFingerprint:reportSourceFingerprint(e)};assert.equal(reportIsStale(report,e),false);e=recordEquityVersion(e,input(),{actor:'Reviewer',actorType:'human',rationale:'اعتماد'}).engagement;assert.equal(reportIsStale(report,e),true)});

test('equity support filename hint matches the EQS intake family but not arbitrary spreadsheets',()=>{const request={requirementId:'EQS',acceptedDocumentTypes:['equity-movement-support']};assert.equal(matchesDocument(request,{type:'spreadsheet',name:'جدول حركة حقوق الملكية 2026.xlsx'}),true);assert.equal(matchesDocument(request,{type:'spreadsheet',name:'تحليل المبيعات.xlsx'}),false)});
