import test from 'node:test';
import assert from 'node:assert/strict';
import { createEngagement } from '../v5/engagement-machine.js';
import { issueSnapshot, issueResolutionReadiness, recordIssueResolution, issueMetrics } from '../v5/issue-workflow.js';

function fixture(){const e=createEngagement({id:'ENG-I'});e.documents.push({id:'DOC-1',name:'bank.pdf'});e.issues.push({id:'ISS-1',title:'فرق في رصيد البنك',severity:'high',status:'open',riskIds:['R-1'],documentIds:['DOC-1'],evidenceIds:[]});e.evidence.push({id:'EVD-1',title:'مصادقة البنك',riskIds:['R-1'],documentIds:['DOC-1'],reviewStatus:'reviewed'});return e}

test('issue snapshot gathers evidence, requests, rounds and adjustments through governed links',()=>{const e=fixture();e.requests.push({id:'REQ-1',title:'كشف التسوية',status:'satisfied',riskIds:['R-1']});e.adjustments.push({id:'AJ-1',title:'تسوية بنك',status:'accepted',issueId:'ISS-1',evidenceIds:['EVD-1']});e.councilRounds.push({id:'RND-1',number:1,issueIds:['ISS-1'],positions:[{seatId:'isa',issueId:'ISS-1',stance:'caution'}]});const s=issueSnapshot(e,'ISS-1');assert.deepEqual(s.evidence.map(x=>x.id),['EVD-1']);assert.deepEqual(s.requests.map(x=>x.id),['REQ-1']);assert.deepEqual(s.adjustments.map(x=>x.id),['AJ-1']);assert.deepEqual(s.rounds.map(x=>x.id),['RND-1']);assert.deepEqual(s.documents.map(x=>x.id),['DOC-1'])});

test('open linked evidence request blocks issue resolution even when reviewed evidence exists',()=>{const e=fixture();e.requests.push({id:'REQ-1',title:'كشف التسوية',status:'requested',riskIds:['R-1']});const ready=issueResolutionReadiness(e,'ISS-1');assert.equal(ready.options['evidence-supported'],false);assert.equal(ready.canResolve,false);assert.throws(()=>recordIssueResolution(e,'ISS-1',{resolutionType:'evidence-supported',actorType:'human',actor:'Manager',rationale:'Reviewed'}),/Open evidence requests/)});

test('reviewed evidence supports an append-only human issue resolution after requests close',()=>{const e=fixture();e.requests.push({id:'REQ-1',title:'كشف التسوية',status:'satisfied',riskIds:['R-1']});const result=recordIssueResolution(e,'ISS-1',{resolutionType:'evidence-supported',actorType:'human',actor:'Manager',rationale:'تمت مطابقة الرصيد بالمصادقة والتسوية'},{at:'2026-09-10T00:00:00Z'});assert.equal(e.issues[0].status,'open');assert.equal(result.engagement.issues[0].status,'closed');assert.deepEqual(result.resolution.evidenceIds,['EVD-1']);assert.equal(result.engagement.issueResolutions.length,1);assert.equal(result.resolution.actorType,'human')});

test('AI/system actors cannot close an issue',()=>{const e=fixture();assert.throws(()=>recordIssueResolution(e,'ISS-1',{resolutionType:'evidence-supported',actorType:'ai',actor:'KOSIF',rationale:'Looks fine'}),/actorType=human/)});

test('accepted adjustment can be the documented human basis for resolving an issue',()=>{const e=fixture();e.evidence[0].reviewStatus='unreviewed';e.adjustments.push({id:'AJ-1',title:'تصحيح الفرق',status:'accepted',issueId:'ISS-1',evidenceIds:[]});const ready=issueResolutionReadiness(e,'ISS-1');assert.equal(ready.options['adjustment-accepted'],true);const result=recordIssueResolution(e,'ISS-1',{resolutionType:'adjustment-accepted',actorType:'human',actor:'Partner',rationale:'اعتمدت الإدارة القيد المصحح'});assert.deepEqual(result.resolution.adjustmentIds,['AJ-1']);assert.equal(result.engagement.issues[0].status,'closed')});

test('not-applicable resolution still requires a human rationale and metrics stop counting it as open',()=>{const e=fixture();e.evidence=[];assert.throws(()=>recordIssueResolution(e,'ISS-1',{resolutionType:'not-applicable',actorType:'human',actor:'Manager',rationale:''}),/rationale is required/);const result=recordIssueResolution(e,'ISS-1',{resolutionType:'not-applicable',actorType:'human',actor:'Manager',rationale:'القضية تخص فترة مختلفة وتم توثيق عدم الانطباق'});assert.equal(result.engagement.issues[0].status,'not-applicable');assert.equal(issueMetrics(result.engagement).open,0);assert.equal(issueMetrics(result.engagement).closed,1)});
