import test from 'node:test';
import assert from 'node:assert/strict';
import { createEngagement } from '../v5/engagement-machine.js';
import { buildProfessionalReportModel } from '../v5/report-model.js';
import { REPORT_RECIPES } from '../v5/report-recipes.js';
import { materialityReportDetail, kamCandidateRows, councilEvolutionRows, evidenceCoverageDetail } from '../v5/report-detail-builders.js';

function engagement(){const e=createEngagement({id:'ENG-R',entity:'شركة اختبار',period:'2026-12-31',engagementType:'audit'});e.documents.push({id:'DOC-1',type:'trial-balance',analysisStatus:'analyzed'});e.issues.push({id:'ISS-1',title:'تقييم العملاء',severity:'high',status:'open',riskIds:['R-1'],standards:['IFRS 9','ISA 540'],assertions:['Valuation'],rationale:'الرصيد جوهري ويعتمد على تقدير'});e.evidence.push({id:'EVD-1',title:'Aging',riskIds:['R-1'],reviewStatus:'reviewed',claim:{assertion:'Valuation'}});e.councilRounds.push({id:'RND-1',number:1,status:'completed',issueIds:['ISS-1'],evidenceIds:['EVD-1'],verdict:'needs-evidence',verdictText:'استكمال فحص التقييم',positions:[{seatId:'isa',title:'ISA',stance:'caution',statement:'يلزم تحدي التقدير'}]});e.requests.push({id:'REQ-1',title:'نموذج ECL',status:'satisfied',priority:'high',riskIds:['R-1'],roundIds:['RND-1'],coverage:100});return e}

test('materiality report detail preserves benchmark, rate, thresholds and rationale',()=>{const m={benchmark:'assets',benchmarkAmount:10000000n,rate:.01,risk:'high',riskMultiplier:.65,overall:65000n,performance:45500n,trivial:3250n,rationale:'اعتماد 1% مع تعديل المخاطر'};const d=materialityReportDetail(m);assert.equal(d.facts.find(x=>x.label==='Benchmark').value,'assets');assert.equal(d.facts.find(x=>x.label==='Overall materiality').value,65000n);assert.match(d.paragraphs[0],/1%/)});

test('KAM candidates remain candidates and carry reviewed evidence plus council provenance',()=>{const e=engagement(),rows=kamCandidateRows(e);assert.equal(rows.length,1);assert.equal(rows[0].reviewedEvidenceCount,1);assert.equal(rows[0].lastCouncilRound,1);assert.ok(rows[0].sourceIds.includes('ISS-1'));assert.ok(rows[0].sourceIds.includes('EVD-1'))});

test('council evolution counts requests born from each round without rewriting history',()=>{const e=engagement(),rows=councilEvolutionRows(e);assert.equal(rows[0].requestsCreated,1);assert.equal(rows[0].openFromRound,0);assert.equal(rows[0].verdict,'استكمال فحص التقييم')});

test('evidence coverage uses reviewed evidence and excludes undeclared assertions',()=>{const e=engagement(),c=evidenceCoverageDetail(e);assert.equal(c.assertionsDeclared,1);assert.equal(c.assertionsCovered,1);assert.equal(c.assertionCoveragePercent,100)});

test('audit report model deepens materiality KAM council and evidence sections but still reserves opinion for human review',()=>{const e=engagement(),m={benchmark:'assets',benchmarkAmount:10000000n,rate:.01,risk:'high',riskMultiplier:.65,overall:65000n,performance:45500n,trivial:3250n,rationale:'اعتماد 1% مع تعديل المخاطر'},model=buildProfessionalReportModel({engagement:e,recipe:REPORT_RECIPES['audit-report'],materiality:m,documentMetrics:{documentsAnalyzed:1,claims:1,risks:1},traceabilityMetrics:{nodes:4,edges:3,isolated:[]}});const materiality=model.sections.find(s=>s.id==='materiality'),kam=model.sections.find(s=>s.id==='key-audit-matters'),council=model.sections.find(s=>s.id==='council-summary'),coverage=model.sections.find(s=>s.id==='evidence-coverage'),opinion=model.sections.find(s=>s.id==='opinion');assert.equal(materiality.humanReviewRequired,true);assert.ok(materiality.facts.some(f=>f.label==='Clearly trivial threshold'));assert.equal(kam.tables[0].headers.includes('لماذا مهمة'),true);assert.equal(council.tables.length,2);assert.ok(coverage.facts.some(f=>f.label==='Assertions مغطاة بدليل مراجع'));assert.equal(opinion.status,'human-required');assert.match(opinion.paragraphs[0],/لا يصدر KOSIF رأيًا نهائيًا/)});
