import test from 'node:test';
import assert from 'node:assert/strict';
import{createEngagement,deriveEngagementStage,ENGAGEMENT_STAGES,nextActionForEngagement,reportReadiness}from'../v5/engagement-machine.js';
import{createEvidenceRequestsFromCouncilRound,evaluateRequestSatisfaction,refreshEvidenceRequests}from'../v5/evidence-requests.js';
import{proposeAdjustment,decideAdjustment,buildAdjustedTrialBalance,validateAdjustment}from'../v5/adjustment-ledger.js';
import{resolveReportIntent,buildReportPlan}from'../v5/report-recipes.js';
import{buildEngagementTraceability,traceAncestors,downstreamImpacts}from'../v5/traceability.js';
import{recordCouncilRound,ingestEvidenceBatch,reviewLoopStatus}from'../v5/review-loop.js';
function baseEngagement(){const e=createEngagement({id:'ENG-TEST',entity:'شركة الاختبار',period:'2026-12-31'});e.documents.push({id:'DOC-1',name:'tb.csv',status:'classified',version:1});e.issues.push({id:'ISS-1',title:'رصيد بنك يحتاج مصادقة',severity:'high',status:'open',evidenceIds:[]});return e}
test('engagement machine moves from intake to planning and evidence workflow',()=>{const e=createEngagement({id:'ENG-1'});assert.equal(deriveEngagementStage(e),ENGAGEMENT_STAGES.INTAKE);e.documents.push({id:'DOC-1',status:'classified'});assert.equal(deriveEngagementStage(e),ENGAGEMENT_STAGES.PLANNING);e.issues.push({id:'ISS-1',title:'اختبار',severity:'high',status:'open'});assert.equal(deriveEngagementStage(e),ENGAGEMENT_STAGES.EVIDENCE_COLLECTION);assert.equal(nextActionForEngagement(e).code,'RESOLVE_ISSUE')});
test('council asks become governed requests and duplicates are suppressed',()=>{const round={id:'RND-001',positions:[{seatId:'isa',stance:'objection',asks:['مصادقة بنك الرياض']},{seatId:'quality',stance:'caution',asks:['مصادقة بنك الرياض']}]};const result=createEvidenceRequestsFromCouncilRound(round,[],{createdAt:'2026-01-01T00:00:00Z'});assert.equal(result.requests.length,1);assert.deepEqual(result.requests[0].requestedBy.sort(),['isa','quality']);assert.equal(result.requests[0].priority,'high')});
test('evidence request can be partially satisfied then satisfied after reviewed evidence',()=>{const request={id:'REQ-0001',title:'مصادقة البنك',status:'requested',evidenceIds:[],acceptanceCriteria:[{id:'relevance',required:true},{id:'period',required:true}]};const partial=evaluateRequestSatisfaction(request,[{id:'EVD-1',requestIds:['REQ-0001'],reviewStatus:'reviewed',criteriaSatisfied:['relevance']}]);assert.equal(partial.status,'partial');assert.equal(partial.coverage,50);const refreshed=refreshEvidenceRequests([request],[{id:'EVD-2',requestIds:['REQ-0001'],reviewStatus:'reviewed',criteriaSatisfied:['relevance','period']}]);assert.equal(refreshed[0].status,'satisfied');assert.equal(refreshed[0].coverage,100)});
test('adjustment ledger rejects unbalanced entries and applies only accepted entries',()=>{assert.equal(validateAdjustment({lines:[{accountId:'A',side:'debit',amountMinor:100n},{accountId:'B',side:'credit',amountMinor:90n}]}).valid,false);let ledger=proposeAdjustment([],{title:'قيد اختبار',lines:[{accountId:'A',side:'debit',amountMinor:100n},{accountId:'B',side:'credit',amountMinor:100n}]},{proposedAt:'2026-01-01T00:00:00Z'});let result=buildAdjustedTrialBalance([{id:'A',debit:1000n,credit:0n},{id:'B',debit:0n,credit:1000n}],ledger);assert.equal(result.totalDebit,1000n);assert.equal(result.totalCredit,1000n);ledger=decideAdjustment(ledger,ledger[0].id,{decision:'accepted',actor:'Mahmoud',rationale:'الدليل كافٍ',decidedAt:'2026-01-02T00:00:00Z'});result=buildAdjustedTrialBalance([{id:'A',debit:1000n,credit:0n},{id:'B',debit:0n,credit:1000n}],ledger);assert.equal(result.totalDebit,1100n);assert.equal(result.totalCredit,1100n);assert.equal(result.balanced,true)});
test('Arabic report intent resolves ميزانية and adapts requirements to account categories',()=>{const recipe=resolveReportIntent('أريد ميزانية 2026');assert.equal(recipe.id,'statement-of-financial-position');const plan=buildReportPlan('أريد ميزانية 2026',{categories:['نقدية وبنوك','مخزون'],documentTypes:['trial-balance']});assert.equal(plan.understood,true);assert.ok(plan.requirements.some(i=>i.id==='BANK'));assert.ok(plan.requirements.some(i=>i.id==='INV'));assert.equal(plan.requirements.find(i=>i.id==='TB').status,'satisfied')});
test('continuous loop creates requests, receives evidence and returns to council review',()=>{const e=baseEngagement();const first=recordCouncilRound(e,{positions:[{seatId:'isa',stance:'objection',issueId:'ISS-1',asks:[{title:'مصادقة البنك',issueId:'ISS-1',priority:'critical'}]}]},{recordedAt:'2026-01-03T00:00:00Z'});assert.equal(first.createdRequests.length,1);assert.equal(first.engagement.stage,ENGAGEMENT_STAGES.AWAITING_EVIDENCE);const req=first.engagement.requests[0];const second=ingestEvidenceBatch(first.engagement,[{title:'مصادقة خارجية',requestIds:[req.id],issueIds:['ISS-1'],reviewStatus:'received',criteriaSatisfied:['relevance','period'],sourceType:'external'}],{receivedAt:'2026-01-04T00:00:00Z'});assert.equal(second.engagement.stage,ENGAGEMENT_STAGES.COUNCIL_REVIEW);assert.equal(reviewLoopStatus(second.engagement).shouldConveneAgain,true)});
test('traceability follows evidence to issue to adjustment to report and computes downstream impact',()=>{const e=baseEngagement();e.documents=[{id:'DOC-1',name:'bank.pdf',status:'classified'}];e.evidence=[{id:'EVD-1',title:'مصادقة',documentIds:['DOC-1'],reviewStatus:'reviewed'}];e.issues=[{id:'ISS-1',title:'فرق بنك',severity:'high',status:'closed',evidenceIds:['EVD-1']}];e.adjustments=[{id:'AJ-0001',title:'تسوية بنك',issueId:'ISS-1',evidenceIds:['EVD-1'],status:'accepted'}];e.reports=[{id:'RPT-1',title:'تقرير',sourceIds:['AJ-0001'],status:'draft',version:1}];const graph=buildEngagementTraceability(e),paths=traceAncestors(graph,'RPT-1');assert.ok(paths.some(path=>path.some(n=>n.id==='DOC-1')&&path.some(n=>n.id==='AJ-0001')));const impacts=downstreamImpacts(graph,['DOC-1']).map(n=>n.id);assert.ok(impacts.includes('RPT-1'))});
test('report readiness blocks critical unavailable evidence',()=>{const e=baseEngagement();e.issues[0].status='closed';e.councilRounds.push({id:'RND-001',status:'completed',conflicts:[]});e.requests.push({id:'REQ-0001',title:'خطاب قانوني',priority:'critical',status:'unavailable'});const readiness=reportReadiness(e);assert.equal(readiness.ready,false);assert.ok(readiness.blockers.some(i=>i.type==='scope_limitation'))});
