import { useEffect, useMemo, useRef, useState } from 'react';
import { downloadTextFile } from '../session-export.js';
import { contextStamp } from '../intelligence/agent.js';
import { createAgentContext } from '../intelligence/context.js';
import { buildLocalAiReview } from '../report-benchmark.js';
import '../intelligence/studio.css';
const roles={assistant:'مساعد ملف المراجعة',ifrs:'مراجع IFRS',isa:'مراجع ISA',fraud:'مراجع الغش',quality:'مراجع الجودة',tax:'مراجع الزكاة والضريبة',goingConcern:'مراجع الاستمرارية',data:'مراجع البيانات',controls:'مراجع الرقابة'};
const errors={provider_model:'النموذج غير موجود أو غير متاح لهذا المفتاح؛ انسخ معرّف النموذج من حساب المزوّد.',provider_request:'رفض المزوّد صيغة الطلب أو إعدادات النموذج؛ راجع توافق النموذج مع هذا الاتصال.',provider_network:'تعذر وصول الخادم إلى المزوّد؛ أعد اختبار الاتصال بعد قليل.',provider_timeout:'انتهت مهلة انتظار المزوّد؛ أعد المحاولة.',origin_rejected:'تعذر التحقق من مصدر الطلب.',ai_storage_unavailable:'خدمة إعداد المفاتيح غير متاحة الآن.',invalid_config:'راجع اسم النموذج والمفتاح والمزوّد.',session_required:'انتهت جلسة الاتصال؛ أضف المفتاح مجددًا.',provider_auth:'رفض المزوّد المفتاح أو الصلاحيات.',provider_quota:'بلغت حصة المزوّد حدها؛ راجع الرصيد أو حدود الطلبات.',provider_error:'رفض المزوّد الطلب؛ تحقق من اسم النموذج وإتاحته.',provider_unconfigured:'أضف مفتاح هذا المزوّد أولًا.',empty_response:'لم يُرجع النموذج نصًا؛ جرّب سؤالًا أقصر.',request_failed:'تعذر إكمال الطلب؛ حاول مجددًا.',request_too_large:'الطلب أكبر من الحد المسموح.'};
export function AiConnections({accounts,engagement,setEngagement,metrics,reportState,onToast,onOpenStandard}) {
 const [registry,setRegistry]=useState(null),[provider,setProvider]=useState('openai'),[model,setModel]=useState(''),[key,setKey]=useState(''),[role,setRole]=useState('assistant'),[question,setQuestion]=useState('راجع أولويات هذا الملف وحدد الأدلة الناقصة وأسئلة التحدي.'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[localReview,setLocalReview]=useState(null);
 const summary=useMemo(()=>({accountCount:accounts.length,balanced:metrics.isBalanced,materialityMinor:metrics.materialityMinor,openFindings:reportState.openFindings,pendingEvidence:reportState.pendingEvidence,completedRounds:engagement.rounds.filter(r=>r.status==='complete').length,totalRounds:engagement.rounds.length,passedGates:reportState.passedGates,totalGates:reportState.gates.length,synthetic:engagement.demo?.synthetic===true}),[accounts,engagement,metrics,reportState]);
 const stamp=useMemo(()=>contextStamp(createAgentContext(accounts,engagement,metrics,reportState)),[accounts,engagement,metrics,reportState]);
 const runs=Array.isArray(engagement.externalAiRuns)?engagement.externalAiRuns:[];
 const companyContext=engagement.aiCompanyContext || null;
 const [health,setHealth]=useState({});
 const [progress,setProgress]=useState('');
 const stopRequested=useRef(false);
 const standardsIn=text=>[...new Set((String(text || '').match(/\b(?:ISA|IAS|IFRS)\s+\d{1,3}\b/g) || []).map(value=>value.replace(/\s+/g,' ')))];
 async function api(path,method='GET',body) {const res=await fetch('/api/ai/'+path,{method,credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw new Error(errors[data.error] || 'تعذر الاتصال بالخدمة.');return data;}
 useEffect(()=>{let active=true;api('config').then(r=>{if(active)setRegistry(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{setRegistry(await api('config','PUT',{provider,model:model.trim(),apiKey:key.trim()}));setKey('');onToast?.('حُفظ المفتاح مشفّرًا في جلسة اتصال خاصة لمدة 24 ساعة.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{setRegistry(await api('config','DELETE'));setKey('');onToast?.('حُذفت مفاتيح جلسة الاتصال.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function run(e){e.preventDefault();setBusy(true);setError('');const sourceStamp=stamp;try{const result=await api('run','POST',{provider,role,question,summary:companyContext?{}:summary,companyContext,consent});setEngagement(current=>({...current,externalAiRuns:[{...result,id:crypto.randomUUID(),question,sourceStamp,summary:companyContext?{}:summary,companyContext},...(current.externalAiRuns || [])].slice(0,40)}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function testConnections(){
  const configured=registry?.providers?.filter(item=>item.configured) || [];
  if(!configured.length)return setError('أضف اتصالًا واحدًا على الأقل قبل الاختبار.');
  setBusy(true);setError('');setProgress('اختبار الاتصالات…');
  for(const item of configured){
   const started=Date.now();
   try{await api('run','POST',{provider:item.id,role:'assistant',question:'هذا اختبار اتصال فقط. أجب بجملة قصيرة تؤكد جاهزيتك للمراجعة الاستشارية.',summary:{},consent:true});setHealth(current=>({...current,[item.id]:{ok:true,latencyMs:Date.now()-started,at:new Date().toISOString()}}));}
   catch(e){setHealth(current=>({...current,[item.id]:{ok:false,message:e.message,at:new Date().toISOString()}}));}
  }
  setBusy(false);setProgress('');onToast?.('اكتمل اختبار المزودات المهيأة؛ راجع نتيجة كل اتصال.');
 }
 async function runCouncil(){
  const configured=registry?.providers?.filter(item=>item.configured) || [];
  if(!consent || !configured.length)return;
  setBusy(true);setError('');stopRequested.current=false;
  const batchId='AI-CR-'+crypto.randomUUID();const sourceStamp=stamp;let failures=0;
  const roleIds=Object.keys(roles);
  for(let index=0;index<roleIds.length;index++){
   if(stopRequested.current)break;
   const assigned=configured[index%configured.length].id;const assignedRole=roleIds[index];
   setProgress('مراجعة '+(index+1)+' من '+roleIds.length+' · '+roles[assignedRole]+' · '+assigned);
   try{const result=await api('run','POST',{provider:assigned,role:assignedRole,question,summary:companyContext?{}:summary,companyContext,consent});setEngagement(current=>({...current,externalAiRuns:[{...result,id:crypto.randomUUID(),question,sourceStamp,summary:companyContext?{}:summary,companyContext,batchId},...(current.externalAiRuns || [])].slice(0,60)}));}
   catch(e){failures++;setError('تعذر '+roles[assignedRole]+': '+e.message);}
  }
  setBusy(false);setProgress('');onToast?.(stopRequested.current?'توقفت الجولة بعد اكتمال الطلب الجاري.':failures?'اكتملت الجولة مع '+failures+' اتصالات لم تنجح؛ النتائج المتاحة محفوظة.':'اكتملت مراجعة الأدوار التسعة وحُفظ كل رد مع مصدره.');
 }
 function runLocal(){setLocalReview(buildLocalAiReview({engagement,metrics,reportState}));onToast?.('شُغّل المراجع المحلي من ملخص الجلسة دون إرسال أي بيانات إلى مزوّد خارجي.');}
 const ready=registry?.providers?.find(p=>p.id===provider)?.configured;
 return <section className="ki-studio"><header className="panel ki-card"><span className="eyebrow">AI Reviewers & Assistants</span><h2>اتصالات المراجعين ومساعدي AI</h2><p>اربط مفتاحك واختر النموذج ودور المراجع. لا يدخل المفتاح في ملفات الارتباط أو تنزيلاتها، ويُحفظ مشفّرًا لمدة 24 ساعة في جلسة خاصة بهذا المتصفح. قد يفرض المزوّد رسوم استخدام.</p></header>{error && <p className="panel ki-card" role="alert">{error}</p>}
 {companyContext && <article className="ki-card"><h3>سياق شركة العرض: {companyContext.companyId} · {companyContext.reportYear}</h3><p>سيُرسل سجل إعادة الحساب لهذه الشركة، وتبقى بيانات الارتباط الحالية خارج الطلب.</p><button type="button" className="button button-outline" onClick={()=>{setEngagement(current=>({...current,aiCompanyContext:null}));setConsent(false);}}>العودة إلى ملف الارتباط الحالي</button></article>}<div className="ki-grid"><form className="ki-card" onSubmit={save}><h3>إضافة API</h3><label>المزوّد<select value={provider} disabled={busy} onChange={e=>{setProvider(e.target.value);setModel('');setKey('');setConsent(false);}}><option value="openai">OpenAI</option><option value="gemini">Google Gemini</option><option value="claude">Anthropic Claude</option></select></label><label>معرّف النموذج<input required maxLength={100} value={model} onChange={e=>setModel(e.target.value)} placeholder="انسخ اسم النموذج المتاح في حساب المزوّد" autoComplete="off"/></label><p>معرّف النموذج هو الاسم الذي يحدده مزوّد API في حسابك، وليس اسمًا شخصيًا للاتصال.</p><label>مفتاح API<input required type="password" autoComplete="new-password" minLength={16} maxLength={2048} value={key} onChange={e=>setKey(e.target.value)}/></label><div className="button-row"><button className="button button-dark" disabled={busy || !registry?.available}>حفظ الاتصال</button><button className="button button-outline" type="button" disabled={busy} onClick={remove}>حذف مفاتيح الجلسة</button></div><p>الحفظ لا يثبت صلاحية المفتاح؛ الاختبار التالي يرسل رسالة جاهزية قصيرة فقط.</p><button className="button button-outline" type="button" disabled={busy || !registry?.providers?.some(p=>p.configured)} onClick={testConnections}>اختبار جميع الاتصالات</button>{registry?.providers?.map(p=><p key={p.id}>{p.id}: {p.configured?'مُعدّ · '+p.model:'غير مُعدّ'}{health[p.id] && <strong> · {health[p.id].ok?'استجاب خلال '+health[p.id].latencyMs+' ms':health[p.id].message}</strong>}</p>)}</form>
 <form className="ki-card" onSubmit={run}><h3>تشغيل مراجعة أو مساعد</h3><label>الدور<select value={role} onChange={e=>{setRole(e.target.value);setConsent(false);}}>{Object.entries(roles).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>السؤال<textarea required maxLength={2000} value={question} onChange={e=>{setQuestion(e.target.value);setConsent(false);}}/></label><details><summary>معاينة الملخص الذي سيُرسل</summary><pre className="ki-preserve">{JSON.stringify(companyContext || summary,null,2)}</pre></details><label className="ki-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> أوافق على إرسال السؤال وهذه المؤشرات إلى المزوّد المحدد.</label><p>لا تُرسل أسماء الحسابات أو ملفات الأدلة. تشغيل المجلس يوزّع الأدوار التسعة على المزودات المهيأة؛ إذا كان مزود واحد فقط فإنه يغطي جميع الأدوار. الإجابات استشارية.</p><div className="button-row"><button className="button button-dark" disabled={busy || !ready || !consent}>{busy?'جارٍ التنفيذ…':'تشغيل المراجع عبر API'}</button><button className="button button-outline" type="button" disabled={busy || !consent || !registry?.providers?.some(p=>p.configured)} onClick={runCouncil}>تشغيل المجلس · 9 مراجعات API</button><button className="button button-outline" type="button" onClick={runLocal}>تشغيل AI محلي للعرض</button>{busy && <button className="button button-outline" type="button" onClick={()=>{stopRequested.current=true;}}>إيقاف بعد الطلب الجاري</button>}{progress && <p role="status">{progress}</p>}</div></form></div>
 {localReview && <article className="ki-card ki-local-review"><h3>{localReview.title}</h3><small>{localReview.mode} · {localReview.generatedAt}</small><p>{localReview.summary}</p>{localReview.findings.map(finding=><div key={finding.title}><strong>{finding.severity} · {finding.title}</strong><p>{finding.rationale}</p><small>الخطوة التالية: {finding.nextStep}</small>{finding.standardId && <button type="button" className="button button-outline" onClick={()=>onOpenStandard?.(finding.standardId)}>{finding.standardId} · فتح المعيار ↗</button>}</div>)}<p>{localReview.guardrail}</p></article>}
 <div><h3>نتائج المراجعين والمساعدين</h3>{runs.length===0 && <p>ستظهر هنا الإجابات الفعلية مع المزوّد والنموذج وبصمة الملف.</p>}{runs.map(r=><article className="ki-card" key={r.id}><h3>{roles[r.role]} · {r.provider}</h3><small>{r.model} · {r.generatedAt} · {r.sourceStamp===stamp?'المصدر مطابق':'تغيّر المصدر؛ راجع حداثة الإجابة'}</small><p>{r.question}</p><p className="ki-preserve">{r.text}</p><div className="button-row">{standardsIn(r.text).map(id=><button key={id} type="button" className="button button-outline" onClick={()=>onOpenStandard?.(id)}>{id} ↗</button>)}</div><button className="button button-outline" onClick={()=>downloadTextFile(JSON.stringify(r,null,2),'kosif-ai-review.json','application/json')}>تنزيل نتيجة المراجعة</button></article>)}</div>
 </section>;
}
