import { useEffect, useMemo, useState } from 'react';
import { downloadTextFile } from '../session-export.js';
import { contextStamp } from '../intelligence/agent.js';
import { createAgentContext } from '../intelligence/context.js';
import '../intelligence/studio.css';
const roles={assistant:'مساعد ملف المراجعة',ifrs:'مراجع IFRS',isa:'مراجع ISA',fraud:'مراجع الغش',quality:'مراجع الجودة',tax:'مراجع الزكاة والضريبة',goingConcern:'مراجع الاستمرارية',data:'مراجع البيانات',controls:'مراجع الرقابة'};
const errors={origin_rejected:'تعذر التحقق من مصدر الطلب.',ai_storage_unavailable:'خدمة إعداد المفاتيح غير متاحة الآن.',invalid_config:'راجع اسم النموذج والمفتاح والمزوّد.',session_required:'انتهت جلسة الاتصال؛ أضف المفتاح مجددًا.',provider_auth:'رفض المزوّد المفتاح أو الصلاحيات.',provider_quota:'بلغت حصة المزوّد حدها؛ راجع الرصيد أو حدود الطلبات.',provider_error:'رفض المزوّد الطلب؛ تحقق من اسم النموذج وإتاحته.',provider_unconfigured:'أضف مفتاح هذا المزوّد أولًا.',empty_response:'لم يُرجع النموذج نصًا؛ جرّب سؤالًا أقصر.',request_failed:'تعذر إكمال الطلب؛ حاول مجددًا.',request_too_large:'الطلب أكبر من الحد المسموح.'};
export function AiConnections({accounts,engagement,setEngagement,metrics,reportState,onToast}) {
 const [registry,setRegistry]=useState(null),[provider,setProvider]=useState('openai'),[model,setModel]=useState(''),[key,setKey]=useState(''),[role,setRole]=useState('assistant'),[question,setQuestion]=useState('راجع أولويات هذا الملف وحدد الأدلة الناقصة وأسئلة التحدي.'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const summary=useMemo(()=>({accountCount:accounts.length,balanced:metrics.isBalanced,materialityMinor:metrics.materialityMinor,openFindings:reportState.openFindings,pendingEvidence:reportState.pendingEvidence,completedRounds:engagement.rounds.filter(r=>r.status==='complete').length,totalRounds:engagement.rounds.length,passedGates:reportState.passedGates,totalGates:reportState.gates.length,synthetic:engagement.demo?.synthetic===true}),[accounts,engagement,metrics,reportState]);
 const stamp=useMemo(()=>contextStamp(createAgentContext(accounts,engagement,metrics,reportState)),[accounts,engagement,metrics,reportState]);
 const runs=Array.isArray(engagement.externalAiRuns)?engagement.externalAiRuns:[];
 async function api(path,method='GET',body) {const res=await fetch('/api/ai/'+path,{method,credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw new Error(errors[data.error] || 'تعذر الاتصال بالخدمة.');return data;}
 useEffect(()=>{let active=true;api('config').then(r=>{if(active)setRegistry(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{setRegistry(await api('config','PUT',{provider,model:model.trim(),apiKey:key.trim()}));setKey('');onToast?.('حُفظ المفتاح مشفّرًا في جلسة اتصال خاصة لمدة 24 ساعة.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{setRegistry(await api('config','DELETE'));setKey('');onToast?.('حُذفت مفاتيح جلسة الاتصال.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function run(e){e.preventDefault();setBusy(true);setError('');const sourceStamp=stamp;try{const result=await api('run','POST',{provider,role,question,summary,consent});setEngagement(current=>({...current,externalAiRuns:[{...result,id:crypto.randomUUID(),question,sourceStamp,summary},...(current.externalAiRuns || [])].slice(0,30)}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 const ready=registry?.providers?.find(p=>p.id===provider)?.configured;
 return <section className="ki-studio"><header className="panel ki-card"><span className="eyebrow">AI Reviewers & Assistants</span><h2>اتصالات المراجعين ومساعدي AI</h2><p>اربط مفتاحك واختر النموذج ودور المراجع. لا يدخل المفتاح في ملفات الارتباط أو تنزيلاتها، ويُحفظ مشفّرًا لمدة 24 ساعة في جلسة خاصة بهذا المتصفح. قد يفرض المزوّد رسوم استخدام.</p></header>{error && <p className="panel ki-card" role="alert">{error}</p>}
 <div className="ki-grid"><form className="ki-card" onSubmit={save}><h3>إضافة API</h3><label>المزوّد<select value={provider} disabled={busy} onChange={e=>{setProvider(e.target.value);setModel('');setKey('');setConsent(false);}}><option value="openai">OpenAI</option><option value="gemini">Google Gemini</option><option value="claude">Anthropic Claude</option></select></label><label>معرّف النموذج<input required maxLength={100} value={model} onChange={e=>setModel(e.target.value)} placeholder="انسخ اسم النموذج المتاح في حساب المزوّد" autoComplete="off"/></label><label>مفتاح API<input required type="password" autoComplete="new-password" minLength={16} maxLength={2048} value={key} onChange={e=>setKey(e.target.value)}/></label><div className="button-row"><button className="button button-dark" disabled={busy || !registry?.available}>حفظ الاتصال</button><button className="button button-outline" type="button" disabled={busy} onClick={remove}>حذف مفاتيح الجلسة</button></div><p>الحفظ لا يثبت صلاحية المفتاح؛ أول تشغيل يختبر الاتصال الفعلي.</p>{registry?.providers?.map(p=><p key={p.id}>{p.id}: {p.configured?`مُعدّ · ${p.model}`:'غير مُعدّ'}</p>)}</form>
 <form className="ki-card" onSubmit={run}><h3>تشغيل مراجعة أو مساعد</h3><label>الدور<select value={role} onChange={e=>{setRole(e.target.value);setConsent(false);}}>{Object.entries(roles).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>السؤال<textarea required maxLength={2000} value={question} onChange={e=>{setQuestion(e.target.value);setConsent(false);}}/></label><details><summary>معاينة الملخص الذي سيُرسل</summary><pre className="ki-preserve">{JSON.stringify(summary,null,2)}</pre></details><label className="ki-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> أوافق على إرسال السؤال وهذه المؤشرات إلى المزوّد المحدد.</label><p>لا تُرسل أسماء الحسابات أو ملفات الأدلة. الإجابة استشارية ولا تغيّر نتائج الجولات أو قرار التقرير.</p><button className="button button-dark" disabled={busy || !ready || !consent}>{busy?'جارٍ التنفيذ…':'تشغيل المراجع عبر API'}</button></form></div>
 <div><h3>نتائج المراجعين والمساعدين</h3>{runs.length===0 && <p>ستظهر هنا الإجابات الفعلية مع المزوّد والنموذج وبصمة الملف.</p>}{runs.map(r=><article className="ki-card" key={r.id}><h3>{roles[r.role]} · {r.provider}</h3><small>{r.model} · {r.generatedAt} · {r.sourceStamp===stamp?'المصدر مطابق':'تغيّر المصدر؛ راجع حداثة الإجابة'}</small><p>{r.question}</p><p className="ki-preserve">{r.text}</p><button className="button button-outline" onClick={()=>downloadTextFile(JSON.stringify(r,null,2),'kosif-ai-review.json','application/json')}>تنزيل نتيجة المراجعة</button></article>)}</div>
 </section>;
}
