import { AiConnections } from './AiConnections.jsx';
import { useMemo, useState } from 'react';
import { createDemo500, demo500ReportText } from '../demo-500.js';
import { buildAccountsCsv, buildTemporarySessionSnapshot, downloadTextFile } from '../session-export.js';
import { createSessionWorkbookBytes, downloadWorkbookBytes } from '../session-workbook.js';
import { formatMinorUnits } from '../audit-core.js';
import { opinionLabels } from '../reporting.js';
import '../intelligence/studio.css';
export function Demo500Workspace({onToast}) {
 const [run,setRun]=useState(0),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 const d=useMemo(()=>createDemo500(),[run]);
 const [showAi,setShowAi]=useState(false),[aiRuns,setAiRuns]=useState([]);
 const [selected,setSelected]=useState('R-001');
 const round=d.rounds.find(r=>r.id===selected);
 async function exportPackage(type) {setBusy(true);try {const snapshot=await buildTemporarySessionSnapshot({accounts:d.accounts,engagement:d.engagement,metrics:d.metrics,dataProfile:d.dataProfile,stages:[]}); if(type==='xlsx') downloadWorkbookBytes((await createSessionWorkbookBytes(snapshot)).bytes,'kosif-500-workpapers.xlsx');else downloadTextFile(JSON.stringify({...snapshot,trainingRoundResults:d.rounds},null,2),'kosif-500-session.json','application/json');}catch(e){onToast?.(e.message);}finally{setBusy(false);}}
 return <section className="ki-studio demo500-screen"><header className="panel ki-card"><span className="eyebrow">500 Accounts · 20 Rounds</span><h2>مختبر المراجعة الكامل — 500 حساب</h2><p>مجتمع متوازن يغطي 20 مجالًا. تُحسب المجتمعات والعينات والتعرضات من الحسابات؛ الأدلة وقرارات الإكمال اصطناعية للتدريب، ولا تغيّر ملف ارتباطك الحالي.</p><div className="button-row"><button className="button button-dark" onClick={()=>setRun(n=>n+1)}>إعادة تنفيذ الجولات العشرين</button><button className="button button-outline" disabled={busy} onClick={()=>exportPackage('xlsx')}>مصنف أوراق العمل Excel</button><button className="button button-outline" disabled={busy} onClick={()=>exportPackage('json')}>كل النتائج JSON</button><button className="button button-outline" onClick={()=>downloadTextFile(buildAccountsCsv(d.accounts,d.engagement.standardMappings),'kosif-500-trial-balance.csv','text/csv')}>الميزان CSV</button><button className="button button-outline" onClick={()=>downloadTextFile(demo500ReportText(d),'kosif-500-audit-report.txt','text/plain')}>تقرير الجولات</button><button className="button button-outline" onClick={()=>setShowAi(v=>!v)}>مراجعة التجربة عبر API</button><button className="button button-outline" onClick={()=>window.print()}>طباعة / PDF</button></div></header>
 <div className="ki-grid">{[['الحسابات',500],['الجولات المنفذة',d.rounds.length],['بوابات السيناريو',`${d.report.passedGates}/${d.report.gates.length}`],['الأهمية النسبية',formatMinorUnits(d.metrics.materialityMinor)]].map(([label,value])=><article className="ki-card" key={label}><p>{label}</p><h2>{value}</h2></article>)}</div>
 <div className="panel ki-card"><h3>المصالحة والتقرير</h3><p>المدين: {formatMinorUnits(d.metrics.totalDebitMinor)} · الدائن: {formatMinorUnits(d.metrics.totalCreditMinor)} · {d.metrics.isBalanced?'متوازن تمامًا':'غير متوازن'}</p><p>الرأي في السيناريو التدريبي: {opinionLabels[d.report.selectedOpinion]} · ثلاث تسويات تدريبية متوازنة.</p><details><summary>بوابات الإصدار ونتيجتها</summary>{d.report.gates.map(g=><p key={g.id}>{g.pass?'✓':'!'} {g.label} — {g.detail}</p>)}</details></div>
 <div className="panel ki-card"><h3>نتائج الجولات</h3><div className="ki-tabs">{d.rounds.map(r=><button key={r.id} className={`button ${r.id===selected?'button-dark':'button-outline'}`} onClick={()=>setSelected(r.id)}>{r.number}. {r.shortLabel}</button>)}</div><h3>{round.title}</h3><p>{round.standards.join(' · ')}</p><p>مجتمع الاختبار: {round.population} حسابًا · عينة موجهة: {round.sampleIds.length} · مخاطر مرتفعة: {round.highRisk}</p><p>الإجراء: {round.action}</p><p>العينة: {round.sampleIds.join('، ')}</p><p>الدليل التدريبي: {round.evidence.id} · النتيجة: {round.finding.title}</p><p>{round.conclusion}</p><small>البصمة: {round.evidence.hash}</small></div>
 <div className="panel ki-card"><h3>الـ500 حساب</h3><label>بحث<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div style={{overflowX:'auto',maxHeight:450}}><table><thead><tr><th>الحساب</th><th>الاسم</th><th>مدين</th><th>دائن</th><th>الخطر</th></tr></thead><tbody>{d.accounts.filter(a=>(a.code+' '+a.name).includes(query)).map(a=><tr key={a.id}><td>{a.code}</td><td>{a.name}</td><td>{formatMinorUnits(a.debitMinor)}</td><td>{formatMinorUnits(a.creditMinor)}</td><td>{a.risk}</td></tr>)}</tbody></table></div></div>
 {showAi && <AiConnections accounts={d.accounts} engagement={{...d.engagement,externalAiRuns:aiRuns}} setEngagement={update=>setAiRuns(update({...d.engagement,externalAiRuns:aiRuns}).externalAiRuns || [])} metrics={d.metrics} reportState={d.report} onToast={onToast}/>}
 <article className="demo500-print-only"><pre>{demo500ReportText(d)}</pre></article>
 <details className="panel ki-card"><summary>التقرير الكامل للجولات العشرين</summary><pre className="ki-preserve">{demo500ReportText(d)}</pre></details>
 </section>;
}
