import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,BookOpen,CheckCircle2,FileSearch,LoaderCircle,Plus,RefreshCw,Send,ShieldCheck,Upload,Volume2} from 'lucide-react';
import {extractAuditDocument,selectedDocumentExcerpts,documentDescriptor,readDocumentIndex,readDocumentRound,retainDocumentRound} from '../document-workbench.js';
import {aiRequest} from '../realtime-client.js';
import '../document-workbench.css';

const roles=['assistant','ifrs','isa','fraud','quality','tax','goingConcern','data','controls'];
const labels={assistant:'مسؤول الملف',ifrs:'خبير IFRS',isa:'خبير ISA',fraud:'محلل الغش',quality:'مراجع الجودة',tax:'الزكاة والضريبة',goingConcern:'الاستمرارية',data:'مراجع البيانات',controls:'الرقابة'};
const hashText=value=>{let hash=2166136261;for(const char of String(value||'')){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16);};
export function DocumentWorkbench({engagement,setEngagement,metrics,reportState,onView,onToast}){
 const saved=engagement.documentLab||{};const savedDocuments=Array.isArray(saved.documents)?saved.documents:[];const savedRounds=Array.isArray(saved.rounds)?saved.rounds:[];const [documents,setDocuments]=useState(savedDocuments);const [rounds,setRounds]=useState([]);const [selectedRole,setSelectedRole]=useState('all');const [provider,setProvider]=useState('');const [providers,setProviders]=useState([]);const [question,setQuestion]=useState('راجع المستندات الحالية، اربط كل نتيجة بالمعيار وسببه، واطلب مستندات محددة عند وجود فجوة.');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [progress,setProgress]=useState('');const [error,setError]=useState('');const [maxPages,setMaxPages]=useState(48);const [pbc,setPbc]=useState('');
 useEffect(()=>{let live=true;aiRequest('config').then(registry=>{if(!live)return;const configured=(registry.providers||[]).filter(item=>item.configured);setProviders(configured);setProvider(configured[0]?.id||'');}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;const descriptors=savedDocuments.filter(Boolean);Promise.all(descriptors.map(async descriptor=>{if(Array.isArray(descriptor.snippets))return descriptor;try{return {...await readDocumentIndex(descriptor),selected:descriptor.selected||[]};}catch(error){return {...descriptor,snippets:[],loadError:error.message};}})).then(items=>{if(live)setDocuments(items);});Promise.all(savedRounds.slice(0,24).map(item=>Array.isArray(item?.results)?item:readDocumentRound(item))).then(items=>{if(live)setRounds(items.filter(Boolean));});return()=>{live=false;};},[savedDocuments.map(item=>item?.id||item?.documentId||'').join('|'),savedRounds.map(item=>item?.id||'').join('|')]);
 const excerpts=useMemo(()=>selectedDocumentExcerpts(documents),[documents]);const save=(next)=>{setEngagement(current=>({...current,documentLab:{...(current.documentLab||{}),...next}}));};
 async function upload(event){const files=[...(event.target.files||[])];event.target.value='';for(const file of files){try{setError('');const doc=await extractAuditDocument(file,{maxPages:Number(maxPages)});const selected=doc.snippets.length?[0]:[];const next=[{...doc,selected},...documents.filter(item=>item.documentId!==doc.documentId)].slice(0,80);setDocuments(next);save({documents:next.map(documentDescriptor)});onToast?.(`تمت فهرسة ${file.name} محليًا؛ اختر المقتطفات قبل إرسال الجولة.`);}catch(e){setError(e.message||'تعذر قراءة المستند.');}}}
 function toggleSnippet(documentId,index){const next=documents.map(doc=>doc.documentId===documentId?{...doc,selected:(doc.selected||[]).includes(index)?(doc.selected||[]).filter(item=>item!==index):[...(doc.selected||[]),index]}:doc);setDocuments(next);save({documents:next.map(documentDescriptor)});setConsent(false);}
 async function runRound(){if(!documents.length)return setError('ارفع مستندًا واحدًا على الأقل.');if(!excerpts.length)return setError('اختر مقتطفًا واحدًا على الأقل.');if(!providers.length||!provider)return setError('أضف اتصال AI في شاشة الاتصالات أولًا.');if(!consent)return setError('وافق على إرسال المقتطفات المختارة إلى المزود.');setBusy(true);setError('');const rolesToRun=selectedRole==='all'?roles:[selectedRole];const roundId=`DOC-R${rounds.length+1}-${Date.now()}`;const sourceStamp=hashText(excerpts.map(item=>`${item.documentId}:${item.page}:${item.text}`).join('|'));const results=[];try{for(let i=0;i<rolesToRun.length;i++){const assigned=providers[i%providers.length].id;setProgress(`الجولة ${rounds.length+1} · ${i+1}/${rolesToRun.length} · ${labels[rolesToRun[i]]||rolesToRun[i]}`);try{const result=await aiRequest('run',{provider:assigned,role:rolesToRun[i],question,summary:{accountCount:metrics.accountCount,balanced:metrics.isBalanced,openFindings:reportState.openFindings,pendingEvidence:reportState.pendingEvidence,completedRounds:engagement.rounds.filter(round=>round.status==='complete').length,totalRounds:engagement.rounds.length},documents:excerpts,documentConsent:true,consent:true});results.push({id:crypto.randomUUID(),role:rolesToRun[i],label:labels[rolesToRun[i]]||rolesToRun[i],...result});}catch(e){results.push({id:crypto.randomUUID(),role:rolesToRun[i],label:labels[rolesToRun[i]]||rolesToRun[i],provider:assigned,error:e.message});}}let chair=null;if(results.length){const digest=results.map(result=>`${result.label}: ${String(result.text||result.error||'').slice(0,180)}`).join('\n').slice(0,1700);try{const result=await aiRequest('run',{provider:providers[0].id,role:'assistant',question:`رأي مرجح مؤقت: قارن آراء المجلس التالية وحدد الاتفاق والخلاف وطلبات الأدلة مع معيار وسبب. هذا تلخيص غير موثوق وليس دليلًا:\n${digest}`,summary:{},documents:excerpts,documentConsent:true,consent:true});chair={id:crypto.randomUUID(),role:'chair',label:'الرأي المرجح · مسؤول الملف',...result};}catch(e){chair={id:crypto.randomUUID(),role:'chair',label:'الرأي المرجح · مسؤول الملف',error:e.message};}}const nextRound={id:roundId,number:rounds.length+1,createdAt:new Date().toISOString(),sourceStamp,question,excerpts,results,chair,requests:[...results,chair].filter(Boolean).flatMap(result=>{const matches=String(result.text||'').match(/(?:المستندات المطلوبة|الأدلة المطلوبة|اطلب)[\s\S]{0,700}/g)||[];return matches.slice(0,3).map(text=>({id:crypto.randomUUID(),text:text.slice(0,700),status:'open'}));})};const next=[nextRound,...rounds];setRounds(next);try{const descriptor=await retainDocumentRound(nextRound);save({rounds:[descriptor,...savedRounds.filter(item=>item.id!==descriptor.id)].slice(0,24)});}catch{save({rounds:next.slice(0,6).map(documentDescriptor)});}onToast?.(`اكتملت الجولة ${nextRound.number}; راجع اختلافات الأعضاء والرأي المرجح وطلبات المستندات.`);}catch(e){setError(e.message||'تعذر تشغيل الجولة.')}finally{setBusy(false);setProgress('');}}
 function addPbc(){const text=pbc.trim().slice(0,500);if(!text)return;const next=[...(saved.manualRequests||[]),{id:crypto.randomUUID(),text,status:'open',createdAt:new Date().toISOString()}];save({manualRequests:next});setPbc('');}
 return <section className="document-workbench panel" aria-labelledby="document-workbench-title"><header className="document-workbench-head"><div><span className="eyebrow"><FileSearch size={14}/> تشغيل المستندات</span><h2 id="document-workbench-title">مختبر مستندات المجلس</h2><p>ارفع مستندات الارتباط وافهرسها محليًا. يرسل المجلس المقتطفات التي تختارها فقط مع رقم الصفحة والبصمة؛ لا تُرسل الملفات الكاملة ولا مفاتيح API.</p></div><label className="button button-gold"><Upload size={17}/> رفع مستندات<input hidden multiple type="file" accept=".pdf,.docx,.xlsx,.xls,.csv,.tsv,.txt,.json,application/pdf" disabled={busy} onChange={upload}/></label></header>
 <div className="document-controls"><label>قراءة PDF<select value={maxPages} onChange={e=>setMaxPages(e.target.value)}><option value="12">12 صفحة للعرض السريع</option><option value="48">48 صفحة + آخر الصفحات</option><option value="160">160 صفحة + آخر الصفحات</option></select></label><label>أعضاء الجولة<select value={selectedRole} onChange={e=>setSelectedRole(e.target.value)}><option value="all">المجلس المفوض · كل الأدوار</option>{roles.map(role=><option key={role} value={role}>{labels[role]||role}</option>)}</select></label><label>المزوّد<select value={provider} onChange={e=>setProvider(e.target.value)}>{providers.map(item=><option key={item.id} value={item.id}>{item.id} · {item.model}</option>)}</select></label></div>
 {error&&<p className="document-error" role="alert"><AlertTriangle size={16}/>{error}</p>}
 {!documents.length?<div className="document-empty"><BookOpen size={28}/><strong>لم تُرفع مستندات بعد</strong><span>ابدأ بميزان، كشف حساب، عقد، فاتورة، تقرير أو كتاب معياري. ستبقى الملفات داخل جهازك حتى تختار مقتطفات وترسلها.</span></div>:<div className="document-list">{documents.map(doc=>{const snippets=Array.isArray(doc.snippets)?doc.snippets:[];return <article className="document-card" key={doc.id}><div className="document-card-head"><span><CheckCircle2 size={17}/><strong>{doc.name}</strong><small>{doc.method} · {doc.pages?`${doc.pages} صفحة · قُرئت ${doc.pagesRead}`:`${snippets.length||doc.snippetCount||0} مقطع`} · بصمة {(doc.documentId||doc.id).slice(0,12)}…</small></span><span className="document-retention">محلي · قابل للحذف</span></div>{doc.loadError&&<p className="document-error"><AlertTriangle size={15}/>{doc.loadError}</p>}<div className="document-snippets">{snippets.slice(0,12).map((item,index)=><label key={`${doc.id}-${index}`} className={(doc.selected||[]).includes(index)?'snippet selected':'snippet'}><input type="checkbox" checked={(doc.selected||[]).includes(index)} onChange={()=>toggleSnippet(doc.documentId,index)}/><span><b>ص {item.page}</b><small>{item.locator}</small>{item.text}</span></label>)}{snippets.length>12&&<small>توجد {snippets.length-12} مقاطع أخرى؛ اختر الأهم للجولة.</small>}{!snippets.length&&!doc.loadError&&<small>جارٍ استعادة الفهرس المحلي…</small>}</div></article>})}</div>}
 <div className="document-round panel"><div className="document-round-head"><div><span className="eyebrow"><RefreshCw size={14}/> جولة قابلة للتكرار</span><h3>شغّل المجلس على المقتطفات المختارة</h3><p>{excerpts.length} مقتطفات · {documents.length} مستندات · المجلس استشاري والقرار البشري مستقل.</p></div><span className="document-round-count">{rounds.length} جولات</span></div><label>سؤال الجولة<textarea value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)}/></label><label className="document-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> أوافق على إرسال المقتطفات الظاهرة فقط إلى OpenAI باستخدام الاتصال المعدّ.</label><button type="button" className="button button-dark" disabled={busy||!consent||!excerpts.length} onClick={runRound}>{busy?<><LoaderCircle className="spin" size={17}/> {progress}</>:<><Send size={17}/> تشغيل الجولة {rounds.length+1}</>}</button></div>
 <div className="document-pbc panel"><div><span className="eyebrow"><Plus size={14}/> طلب مستند إضافي</span><h3>قائمة PBC</h3><p>يضيف المجلس طلباته تلقائيًا من ردود الأعضاء؛ أضف طلبًا يدويًا قبل الجولة التالية.</p></div><div className="document-pbc-add"><input value={pbc} maxLength={500} onChange={e=>setPbc(e.target.value)} placeholder="مثال: كشف أعمار الذمم مع المصادقات حتى 31 ديسمبر"/><button type="button" className="button button-outline" onClick={addPbc}>إضافة</button></div>{(saved.manualRequests||[]).map(item=><p className="pbc-row" key={item.id}><ShieldCheck size={15}/>{item.text}<small>{item.status}</small></p>)}</div>
 {rounds.length>0&&<div className="document-rounds"><h3>سجل الجولات</h3>{rounds.map(round=><details className="document-round-record" key={round.id} open={round.number===rounds[0].number}><summary><strong>الجولة {round.number}</strong><span>{round.createdAt} · {round.results.length} آراء · بصمة {round.sourceStamp}</span></summary><p>{round.question}</p>{round.chair&&<article className="document-chair"><h4>{round.chair.label} <small>{round.chair.provider} · ترجيح استشاري</small></h4><p>{round.chair.text||round.chair.error}</p>{round.chair.text&&<button className="button button-outline" type="button" onClick={()=>localRead(round.chair.text)}><Volume2 size={15}/> قراءة الرأي محليًا</button>}</article>}<div className="document-opinions">{round.results.map(result=><article key={result.id}><h4>{result.label} <small>{result.provider} · {result.model}</small></h4><p>{result.text||result.error}</p><span className="opinion-advisory">رأي استشاري مستقل · افتح المعيار من المجلس للتحقق</span>{result.text&&<button className="button button-outline" type="button" onClick={()=>localRead(result.text)}><Volume2 size={15}/> قراءة</button>}</article>)}</div>{round.requests?.map(item=><p className="pbc-row" key={item.id}><Plus size={15}/>{item.text}</p>)}</details>)}</div>}
 </section>;
}
