import {useEffect,useRef,useState} from 'react';
import {Mic,MicOff,Phone,PhoneOff,Send,Square} from 'lucide-react';
import {aiRequest,createRealtimeClient} from '../realtime-client.js';

export function RealtimeVoice({onView,summary={}}) {
 const [status,setStatus]=useState('idle'),[message,setMessage]=useState('أضف مفتاح OpenAI ثم ابدأ محادثة صوتية.'),[ready,setReady]=useState(false),[consent,setConsent]=useState(false),[shareSummary,setShareSummary]=useState(false),[model,setModel]=useState('gpt-realtime-2.1'),[voice,setVoice]=useState('marin'),[muted,setMuted]=useState(false),[blocked,setBlocked]=useState(false),[messages,setMessages]=useState([]),[text,setText]=useState('');
 const client=useRef(null),viewRef=useRef(onView);viewRef.current=onView;const active=status==='connecting'||status==='connected';
 useEffect(()=>{let live=true;aiRequest('config').then(registry=>{if(live){const configured=registry.providers?.some(p=>p.id==='openai'&&p.configured);setReady(configured);setMessage(configured?'اتصال OpenAI مُعد؛ ابدأ المحادثة لاختبار الصوت.':'أضف مفتاح OpenAI من اتصالات AI أولًا.');}}).catch(e=>{if(live)setMessage(e.message);});client.current=createRealtimeClient({onView:view=>viewRef.current?.(view),onStatus:(state,label)=>{if(live){setStatus(state);setMessage(label);}},onAudioBlocked:()=>{if(live)setBlocked(true);},onTranscript:item=>{if(!live)return;setMessages(current=>{const index=current.findIndex(row=>row.id===item.id);if(index<0)return [...current,{...item,text:item.text.slice(0,12000)}].slice(-60);return current.map((row,i)=>i===index?{...item,text:(item.done?item.text:row.text+item.text).slice(0,12000)}:row);});}});return()=>{live=false;client.current?.disconnect(false);};},[]);
 async function start(){setMuted(false);setBlocked(false);setMessages([]);try{await client.current.connect({model,voice,consent,shareSummary,summary});}catch{}}
 return <div className="realtime-voice"><p className="voice-console-status" role="status">{message}</p>{!active&&<><button className="button button-outline" type="button" onClick={()=>onView?.('ai-connections')}>إعداد مفتاح OpenAI</button><div className="voice-model-fields"><label>نموذج الصوت<input value={model} maxLength={80} onChange={e=>setModel(e.target.value)} dir="ltr"/></label><label>الصوت<select value={voice} onChange={e=>setVoice(e.target.value)}><option value="marin">Marin</option><option value="cedar">Cedar</option><option value="alloy">Alloy</option></select></label></div><label className="voice-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> أوافق على إرسال صوتي ونص المحادثة إلى OpenAI باستخدام مفتاحي؛ تطبق رسوم المزوّد.</label><label className="voice-consent"><input type="checkbox" checked={shareSummary} onChange={e=>setShareSummary(e.target.checked)}/> مشاركة مؤشرات الملف العددية لشرحها أثناء الحديث.</label>{shareSummary&&<details><summary>معاينة المؤشرات</summary><pre>{JSON.stringify(summary,null,2)}</pre></details>}</>}{<div className="voice-console-actions">{active?<><button type="button" className="button button-dark" onClick={()=>client.current.disconnect()}><PhoneOff size={16}/> إنهاء المحادثة</button>{status==='connected'&&<><button type="button" className="button button-outline" onClick={()=>{client.current.setMuted(!muted);setMuted(!muted);}}>{muted?<MicOff size={16}/>:<Mic size={16}/>} {muted?'فتح الميكروفون':'كتم الميكروفون'}</button><button type="button" className="button button-outline" onClick={()=>client.current.interrupt()}><Square size={16}/> مقاطعة الرد</button></>}</>:<button type="button" className="button button-gold" disabled={!consent||!ready||!model} onClick={start}><Phone size={16}/> بدء محادثة حية</button>}</div>}{blocked&&<button className="button button-outline" onClick={()=>Promise.resolve(client.current.playAudio()).then(()=>setBlocked(false)).catch(()=>{})}>تفعيل سماع الرد</button>}{messages.length>0&&<div className="voice-dialogue" role="log" aria-label="نص المحادثة الحية">{messages.map(item=><p key={item.id}><strong>{item.role==='user'?'أنت':'KOSIF AI'}</strong><span>{item.text}</span></p>)}</div>}{status==='connected'&&<form className="voice-text-form" onSubmit={e=>{e.preventDefault();if(client.current.sendText(text))setText('');}}><label className="sr-only" htmlFor="realtime-text">رسالة أثناء المحادثة</label><input id="realtime-text" value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="أو اكتب سؤالك هنا…"/><button className="button button-outline" disabled={!text.trim()}><Send size={16}/></button></form>}<small className="voice-console-disclosure">هذا صوت مولّد بالذكاء الاصطناعي. يمكنك المقاطعة والتنقل بين الشاشات؛ إغلاق اللوحة ينهي الاتصال. لا يُحفَظ تسجيل صوتي في التطبيق.</small></div>;
}
