// KOSIF V5 — authenticated D1 persistence for engagement workspace state.
const MAX_STATE_BYTES=1_800_000;
let schemaReady=false;
const json=(data,{status=200,headers={}}={})=>Response.json(data,{status,headers});
const origins=v=>String(v||'*').split(',').map(x=>x.trim()).filter(Boolean);
function originAllowed(origin,env){const allowed=origins(env.PERSISTENCE_ALLOWED_ORIGIN||env.ALLOWED_ORIGIN);return !origin||allowed.includes('*')||allowed.includes(origin)}
function cors(origin,env){const allowed=origins(env.PERSISTENCE_ALLOWED_ORIGIN||env.ALLOWED_ORIGIN),resolved=allowed.includes('*')?'*':(origin&&allowed.includes(origin)?origin:(allowed[0]||'null'));return{'Access-Control-Allow-Origin':resolved,'Access-Control-Allow-Methods':'POST,PUT,OPTIONS,GET','Access-Control-Allow-Headers':'Content-Type,Accept,Authorization','Access-Control-Max-Age':'86400','Vary':'Origin'}}
function bearer(req){const m=(req.headers.get('Authorization')||'').match(/^Bearer\s+(.+)$/i);return m?.[1]?.trim()||null}
function randomToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256(value){const bytes=typeof value==='string'?new TextEncoder().encode(value):value,d=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function equal(a='',b=''){a=String(a);b=String(b);if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function clean(v,max=200){return String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
async function ensureSchema(env){if(!env.KOSIF_DB?.prepare)return false;if(schemaReady)return true;const sql=[
`CREATE TABLE IF NOT EXISTS engagements (id TEXT PRIMARY KEY, entity_name TEXT, period_end TEXT, jurisdiction TEXT, framework TEXT, created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, engagement_id TEXT NOT NULL, name TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes INTEGER NOT NULL, sha256 TEXT NOT NULL, storage_key TEXT, document_type TEXT NOT NULL, created_at TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS idx_documents_engagement ON documents(engagement_id, created_at DESC)`,
`CREATE TABLE IF NOT EXISTS document_analyses (document_id TEXT PRIMARY KEY, model TEXT, response_id TEXT, analysis_json TEXT NOT NULL, created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS claims (id TEXT PRIMARY KEY, document_id TEXT NOT NULL, kind TEXT NOT NULL, label TEXT NOT NULL, value_text TEXT, amount_minor TEXT, currency TEXT, page INTEGER, confidence TEXT NOT NULL, assertion_name TEXT, account_hint TEXT, created_at TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS idx_claims_document ON claims(document_id)`,
`CREATE TABLE IF NOT EXISTS engagement_sessions (engagement_id TEXT PRIMARY KEY, access_token_hash TEXT NOT NULL, state_json TEXT, state_hash TEXT, state_version INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS engagement_events (engagement_id TEXT NOT NULL, sequence INTEGER NOT NULL, event_type TEXT NOT NULL, object_type TEXT, object_id TEXT, payload_hash TEXT, created_at TEXT NOT NULL, PRIMARY KEY (engagement_id, sequence))`,
`CREATE INDEX IF NOT EXISTS idx_engagement_events_created ON engagement_events(engagement_id, created_at DESC)`];if(env.KOSIF_DB.batch)await env.KOSIF_DB.batch(sql.map(s=>env.KOSIF_DB.prepare(s)));else for(const s of sql)await env.KOSIF_DB.prepare(s).run();schemaReady=true;return true}
async function authorize(req,env,id){if(!await ensureSchema(env))return{error:'d1_not_configured',status:503};const token=bearer(req);if(!token)return{error:'authorization_required',status:401};const row=await env.KOSIF_DB.prepare(`SELECT access_token_hash, state_version, state_hash, state_json FROM engagement_sessions WHERE engagement_id=?`).bind(id).first();if(!row)return{error:'engagement_not_found',status:404};if(!equal(await sha256(token),row.access_token_hash))return{error:'invalid_engagement_token',status:403};return{row}}
async function create(req,env,headers){if(!await ensureSchema(env))return json({error:'d1_not_configured'},{status:503,headers});if(!(req.headers.get('Content-Type')||'').includes('application/json'))return json({error:'application_json_required'},{status:415,headers});const body=await req.json().catch(()=>({})),id=`ENG-${crypto.randomUUID().toUpperCase()}`,token=randomToken(),tokenHash=await sha256(token),now=new Date().toISOString();await env.KOSIF_DB.prepare(`INSERT INTO engagements (id,entity_name,period_end,jurisdiction,framework,created_at) VALUES (?,?,?,?,?,?)`).bind(id,clean(body.entity||body.entityName||'منشأة غير محددة'),clean(body.periodEnd||body.period||'',40)||null,clean(body.jurisdiction||'SA',40),clean(body.framework||'IFRS',60),now).run();await env.KOSIF_DB.prepare(`INSERT INTO engagement_sessions (engagement_id,access_token_hash,state_json,state_hash,state_version,created_at,updated_at) VALUES (?,?,NULL,NULL,0,?,?)`).bind(id,tokenHash,now,now).run();return json({ok:true,engagementId:id,accessToken:token,version:0,createdAt:now,security:{tokenReturnedOnce:true,optimisticConcurrency:true}},{status:201,headers})}
async function get(req,env,id,headers){const a=await authorize(req,env,id);if(a.error)return json({error:a.error},{status:a.status,headers});const meta=await env.KOSIF_DB.prepare(`SELECT id,entity_name,period_end,jurisdiction,framework,created_at FROM engagements WHERE id=?`).bind(id).first();let state=null;if(a.row.state_json)try{state=JSON.parse(a.row.state_json)}catch{return json({error:'stored_state_corrupt'},{status:500,headers})}return json({ok:true,engagement:meta,state,version:Number(a.row.state_version||0),stateHash:a.row.state_hash||null},{headers})}
async function put(req,env,id,headers){const a=await authorize(req,env,id);if(a.error)return json({error:a.error},{status:a.status,headers});const body=await req.json().catch(()=>null);if(!body||typeof body.state!=='object'||body.state===null)return json({error:'state_required'},{status:400,headers});const expected=Number(body.expectedVersion);if(!Number.isInteger(expected)||expected<0)return json({error:'expected_version_required'},{status:400,headers});const current=Number(a.row.state_version||0);if(current!==expected)return json({error:'version_conflict',currentVersion:current,stateHash:a.row.state_hash||null},{status:409,headers});const embedded=body.state?.payload?.engagement?.id;if(embedded&&embedded!==id)return json({error:'engagement_id_mismatch'},{status:409,headers});const stateJson=JSON.stringify(body.state),bytes=new TextEncoder().encode(stateJson).byteLength;if(bytes>MAX_STATE_BYTES)return json({error:'state_too_large',maxBytes:MAX_STATE_BYTES,size:bytes},{status:413,headers});const stateHash=await sha256(stateJson),now=new Date().toISOString(),version=current+1,res=await env.KOSIF_DB.prepare(`UPDATE engagement_sessions SET state_json=?,state_hash=?,state_version=?,updated_at=? WHERE engagement_id=? AND state_version=?`).bind(stateJson,stateHash,version,now,id,current).run();if(Number(res?.meta?.changes??res?.changes??1)===0){const r=await env.KOSIF_DB.prepare(`SELECT state_version,state_hash FROM engagement_sessions WHERE engagement_id=?`).bind(id).first();return json({error:'version_conflict',currentVersion:Number(r?.state_version||0),stateHash:r?.state_hash||null},{status:409,headers})}const eventHash=await sha256(`${id}|${version}|${stateHash}`);await env.KOSIF_DB.prepare(`INSERT INTO engagement_events (engagement_id,sequence,event_type,object_type,object_id,payload_hash,created_at) VALUES (?,?,'STATE_SNAPSHOT_SAVED','ENGAGEMENT',?,?,?)`).bind(id,version,id,eventHash,now).run();return json({ok:true,engagementId:id,version,stateHash,savedAt:now},{headers})}
async function events(req,env,id,headers){const a=await authorize(req,env,id);if(a.error)return json({error:a.error},{status:a.status,headers});const r=await env.KOSIF_DB.prepare(`SELECT sequence,event_type,object_type,object_id,payload_hash,created_at FROM engagement_events WHERE engagement_id=? ORDER BY sequence DESC LIMIT 100`).bind(id).all();return json({ok:true,events:r.results||[]},{headers})}
export function persistenceHealth(env){return{configured:Boolean(env.KOSIF_DB),maxStateBytes:MAX_STATE_BYTES,optimisticConcurrency:true,access:'per-engagement bearer token'}}
export async function handleEngagementApi(req,env){const url=new URL(req.url),origin=req.headers.get('Origin'),headers=cors(origin,env);if(!originAllowed(origin,env))return json({error:'origin_not_allowed'},{status:403,headers});if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(url.pathname==='/api/engagements'&&req.method==='POST')return create(req,env,headers);let m=url.pathname.match(/^\/api\/engagements\/([^/]+)\/state$/);if(m&&req.method==='PUT')return put(req,env,decodeURIComponent(m[1]),headers);m=url.pathname.match(/^\/api\/engagements\/([^/]+)\/events$/);if(m&&req.method==='GET')return events(req,env,decodeURIComponent(m[1]),headers);m=url.pathname.match(/^\/api\/engagements\/([^/]+)$/);if(m&&req.method==='GET')return get(req,env,decodeURIComponent(m[1]),headers);return null}
export{MAX_STATE_BYTES,originAllowed,equal};
