import { areaProfiles } from "./standards.js";
import { sha256HexSync } from "./governance.js";

export const REQUIRED_AUDIT_ROUND_COUNT = 20;

const blueprints = [
  {
    title: "التخطيط وفهم المنشأة",
    shortLabel: "التخطيط",
    risk: "high",
    threshold: 250_000,
    standards: ["ISA 200", "ISA 210", "ISA 300"],
    categoryKeys: ["equity"],
    assertions: ["الاكتمال", "العرض"],
    owner: "شريك الارتباط",
    findingTitle: "الحاجة إلى توثيق أعمق لعوامل قبول الارتباط",
    findingSummary: "اكتملت متطلبات القبول، مع تعزيز توثيق فهم الملكية والحوكمة قبل بدء الاختبارات.",
    action: "ربط مذكرة التخطيط بهيكل الملكية ومحاضر الحوكمة واعتمادها من شريك الارتباط.",
  },
  {
    title: "المخاطر والرقابة الداخلية",
    shortLabel: "الرقابة",
    risk: "high",
    threshold: 375_000,
    standards: ["ISA 315", "ISA 330", "ISA 265"],
    categoryKeys: ["payables"],
    assertions: ["الاكتمال", "الدقة"],
    owner: "مدير المراجعة",
    findingTitle: "تفاوت في توثيق مراجعات صلاحيات المشتريات",
    findingSummary: "أظهرت عينة الرقابة حاجةً لتوحيد أثر المراجعة الدورية لصلاحيات الاعتماد.",
    action: "إرفاق سجل المراجعة الربع سنوي وإثبات اعتماد مسؤول مستقل.",
  },
  {
    title: "الغش والإيرادات",
    shortLabel: "الغش-والإيرادات",
    risk: "high",
    threshold: 500_000,
    standards: ["ISA 240", "IFRS 15"],
    categoryKeys: ["revenue"],
    assertions: ["الحدوث", "القطع"],
    owner: "فريق الإيرادات",
    findingTitle: "استثناء قطع في عقود إيراد مختارة",
    findingSummary: "تم تحديد فرق توقيت في عينة محدودة من العقود المحيطة بتاريخ الإقفال.",
    quantifiedAmount: 412_800,
    quantifiedBasis: "قيد التسوية AJE-002 · فرق القطع المحدد في العينة",
    action: "إعادة تنفيذ اختبار القطع وربط التسوية بالعقد والفاتورة وإثبات التسليم.",
  },
  {
    title: "الأهمية النسبية والعينات",
    shortLabel: "الأهمية-والعينات",
    risk: "high",
    threshold: 625_000,
    standards: ["ISA 320", "ISA 450", "ISA 530"],
    categoryKeys: ["expenses", "cogs"],
    assertions: ["الاكتمال", "الدقة"],
    owner: "المراجع الفني",
    findingTitle: "انحراف عينة يتطلب توسيع الاختبار",
    findingSummary: "تجاوز انحراف واحد الحد المتوقع للعينة، فتم توسيع المجتمع واختبار عناصر إضافية.",
    action: "توثيق أساس التوسيع وتقييم الأثر الإجمالي للتحريفات المكتشفة.",
  },
  {
    title: "النقد والبنوك",
    shortLabel: "النقد-والبنوك",
    risk: "high",
    threshold: 750_000,
    standards: ["ISA 505", "ISA 500", "IAS 7"],
    categoryKeys: ["cash"],
    assertions: ["الوجود", "الحقوق"],
    owner: "فريق الاختبارات",
    findingTitle: "تأخر مصادقة حساب بنكي",
    findingSummary: "وردت المصادقة بعد متابعة ثانية وتمت مطابقتها مع كشف البنك والتسوية.",
    action: "حفظ المصادقة المستقلة ونتيجة المطابقة ضمن ملف الجولة.",
  },
  {
    title: "الذمم والخسائر الائتمانية",
    shortLabel: "الذمم-والائتمان",
    risk: "medium",
    threshold: 875_000,
    standards: ["IFRS 9", "IFRS 7", "ISA 540"],
    categoryKeys: ["receivables"],
    assertions: ["الوجود", "التقييم"],
    owner: "فريق الائتمان",
    findingTitle: "افتراض متفائل في مصفوفة الخسائر الائتمانية",
    findingSummary: "عُدلت فرضية التعثر لعميل رئيس بعد فحص التحصيلات اللاحقة والمعلومات المستقبلية.",
    quantifiedAmount: 684_250,
    quantifiedBasis: "قيد التسوية AJE-003 · فرق إعادة احتساب المخصص",
    action: "ربط النموذج المعدل بمصادر الافتراضات ومراجعة الحساسية.",
  },
  {
    title: "المخزون",
    shortLabel: "المخزون",
    risk: "medium",
    threshold: 1_000_000,
    standards: ["IAS 2", "ISA 501"],
    categoryKeys: ["inventory"],
    assertions: ["الوجود", "التقييم"],
    owner: "فريق المخزون",
    findingTitle: "بند بطيء الحركة يحتاج مخصصًا",
    findingSummary: "أسفر فحص الحركة اللاحقة عن تحديث مخصص التقادم لبند محدد.",
    quantifiedAmount: 185_750,
    quantifiedBasis: "قيد التسوية AJE-001 · فرق الجرد والتقادم المحدد",
    action: "مطابقة سجل الجرد مع المبيعات اللاحقة واعتماد تسوية المخصص.",
  },
  {
    title: "الأصول الثابتة والانخفاض",
    shortLabel: "الأصول-والانخفاض",
    risk: "medium",
    threshold: 1_125_000,
    standards: ["IAS 16", "IAS 36", "IAS 23"],
    categoryKeys: ["ppe"],
    assertions: ["الوجود", "التقييم"],
    owner: "فريق الأصول",
    findingTitle: "مؤشر انخفاض لأصل تشغيلي",
    findingSummary: "تم فحص مؤشر الانخفاض وتحديث العمر الإنتاجي والقيمة القابلة للاسترداد.",
    action: "حفظ نموذج القيمة قيد الاستخدام وموافقة المراجع الفني على الافتراضات.",
  },
  {
    title: "الإيجارات",
    shortLabel: "الإيجارات",
    risk: "medium",
    threshold: 1_250_000,
    standards: ["IFRS 16", "ISA 500"],
    categoryKeys: ["rightOfUse", "leaseLiabilities"],
    assertions: ["الاكتمال", "التقييم"],
    owner: "فريق الالتزامات",
    findingTitle: "عقد تجديد لم يدخل سجل الإيجارات",
    findingSummary: "أضيف عقد تجديد إلى مجتمع الإيجارات وأعيد احتساب أصل حق الاستخدام والالتزام.",
    action: "ربط سجل العقود بقيود الدفتر واختبار اكتمال العقود الجديدة والمعدلة.",
  },
  {
    title: "الاستثمارات والقيمة العادلة",
    shortLabel: "الاستثمارات-والقيمة",
    risk: "medium",
    threshold: 1_375_000,
    standards: ["IFRS 9", "IFRS 13", "ISA 620"],
    categoryKeys: ["investmentProperty"],
    assertions: ["الوجود", "التقييم"],
    owner: "المراجع الفني",
    findingTitle: "حساسية مرتفعة لافتراض الخصم",
    findingSummary: "أُجري تحليل حساسية مستقل وافق نطاق تقييم الخبير بعد تسوية مدخل واحد.",
    action: "توثيق كفاءة الخبير ومصدر مدخلات السوق وتحليل الحساسية.",
  },
  {
    title: "الأصول غير الملموسة",
    shortLabel: "الأصول-غير-الملموسة",
    risk: "medium",
    threshold: 1_500_000,
    standards: ["IFRS 3", "IAS 38", "IAS 36"],
    categoryKeys: ["intangibles"],
    assertions: ["الوجود", "التقييم"],
    owner: "فريق الأصول",
    findingTitle: "حاجة إلى إعادة تقييم العمر النافع",
    findingSummary: "أُعيد تقييم العمر النافع لأصل تقني وربط القرار بخطة الاستخدام المستقبلية.",
    action: "اعتماد مذكرة العمر النافع وربطها باختبار الانخفاض والإفصاح.",
  },
  {
    title: "الموظفون والمنافع",
    shortLabel: "الموظفون-والمنافع",
    risk: "medium",
    threshold: 1_625_000,
    standards: ["IAS 19", "IFRS 2", "ISA 540"],
    categoryKeys: ["employeeBenefits"],
    assertions: ["الاكتمال", "التقييم"],
    owner: "فريق الموظفين",
    findingTitle: "مدخل اكتواري يحتاج تحديثًا",
    findingSummary: "تم تحديث معدل دوران الموظفين ومطابقة المجتمع مع سجل الموارد البشرية.",
    action: "توثيق مصدر المدخل ومراجعة حساب الخبير والحساسية.",
  },
  {
    title: "المخصصات والدعاوى",
    shortLabel: "المخصصات-والدعاوى",
    risk: "medium",
    threshold: 1_750_000,
    standards: ["IAS 37", "ISA 501"],
    categoryKeys: ["provisions"],
    assertions: ["الاكتمال", "التقييم"],
    owner: "فريق الالتزامات",
    findingTitle: "رد قانوني متأخر لدعوى قائمة",
    findingSummary: "ورد رد المستشار القانوني وأكد نطاق الالتزام والإفصاح ذي الصلة.",
    action: "حفظ الرد المستقل ومطابقته مع سجل القضايا ومذكرة المخصص.",
  },
  {
    title: "الضرائب والزكاة",
    shortLabel: "الضرائب-والزكاة",
    risk: "medium",
    threshold: 1_875_000,
    standards: ["IAS 12", "IFRIC 23", "SOCPA ZAKAT"],
    categoryKeys: ["tax"],
    assertions: ["الاكتمال", "الدقة"],
    owner: "فريق الضرائب",
    findingTitle: "فرق في مطابقة الضريبة المؤجلة والزكاة",
    findingSummary: "عولج فرق تصنيفي بعد مطابقة الإقرارات والأساس الضريبي والزكوي.",
    action: "حفظ المصالحة المعتمدة وفصل ضريبة القيمة المضافة عن نطاق IAS 12.",
  },
  {
    title: "الأطراف ذات العلاقة",
    shortLabel: "الأطراف-ذات-العلاقة",
    risk: "low",
    threshold: 2_000_000,
    standards: ["IAS 24", "ISA 550"],
    categoryKeys: ["otherIncome"],
    assertions: ["الاكتمال", "العرض"],
    owner: "فريق الحوكمة",
    findingTitle: "استكمال وصف معاملة طرف ذي علاقة",
    findingSummary: "استُكمل وصف طبيعة المعاملة وشروطها ورصيدها في مسودة الإفصاح.",
    action: "مطابقة الإقرار مع السجل التجاري ومحاضر المجلس ومسودة الإيضاح.",
  },
  {
    title: "التجميع والاستثمارات",
    shortLabel: "التجميع-والاستثمارات",
    risk: "low",
    threshold: 2_125_000,
    standards: ["IFRS 10", "IAS 28", "IFRS 12"],
    categoryKeys: ["debt"],
    assertions: ["الاكتمال", "العرض"],
    owner: "فريق التجميع",
    findingTitle: "فرق تصنيف في قيد استبعاد تجميعي",
    findingSummary: "صُحح تصنيف قيد الاستبعاد دون تغيير صافي أثر التجميع.",
    action: "ربط القيد بحزمة التقارير ومطابقة أرصدة الشركات التابعة.",
  },
  {
    title: "الأحداث اللاحقة والاستمرارية",
    shortLabel: "الأحداث-والاستمرارية",
    risk: "low",
    threshold: 2_250_000,
    standards: ["ISA 560", "ISA 570", "IAS 10"],
    categoryKeys: ["contractLiabilities"],
    assertions: ["الاكتمال", "العرض"],
    owner: "فريق الإقفال",
    findingTitle: "حدث لاحق غير معدل يحتاج إفصاحًا",
    findingSummary: "أضيف الإفصاح عن حدث لاحق غير معدل بعد فحص الفترة اللاحقة.",
    action: "تحديث قائمة الأحداث حتى تاريخ التقرير وربط قرار التصنيف بالمذكرة.",
  },
  {
    title: "العرض والإفصاحات",
    shortLabel: "العرض-والإفصاحات",
    risk: "low",
    threshold: 2_375_000,
    standards: ["IAS 1", "IFRS 18", "IAS 33", "IFRS 8"],
    categoryKeys: ["financeCosts"],
    assertions: ["التصنيف", "العرض"],
    owner: "المراجع الفني",
    findingTitle: "إعادة تصنيف تكلفة تمويل في العرض",
    findingSummary: "عُدلت خريطة العرض لتفصل تكاليف التمويل عن المصروفات التشغيلية.",
    action: "إعادة تشغيل قائمة الإفصاح ومطابقة المجاميع مع الإيضاحات.",
  },
  {
    title: "الأدلة النهائية والإقرارات",
    shortLabel: "الأدلة-والإقرارات",
    risk: "low",
    threshold: 2_500_000,
    standards: ["ISA 580", "ISA 520", "ISA 500"],
    categoryKeys: ["payables"],
    assertions: ["الاكتمال", "العرض"],
    owner: "مدير المراجعة",
    findingTitle: "تحديث صياغة إقرار الإدارة",
    findingSummary: "استُكملت الإشارة إلى التحريفات غير المصححة والأحداث اللاحقة في الإقرار.",
    action: "توقيع الإقرار في تاريخ التقرير وربطه بقائمة الإكمال النهائية.",
  },
  {
    title: "تكوين الرأي والتقرير",
    shortLabel: "الرأي-والتقرير",
    risk: "low",
    threshold: 2_625_000,
    standards: ["ISA 700", "ISA 701", "ISA 705", "ISA 706"],
    categoryKeys: ["revenue"],
    assertions: ["العرض", "الاكتمال"],
    owner: "شريك الارتباط",
    findingTitle: "تحسين توثيق أساس الرأي",
    findingSummary: "اكتملت مذكرة أساس الرأي بعد ربط الاستنتاجات بالأدلة والتسويات والقرار البشري.",
    action: "إجراء مراجعة الجودة النهائية ثم توثيق مدخلات ISA 705 واعتماد الرأي المشتق.",
  },
];

export const auditRoundBlueprints = Object.freeze(blueprints.map((round, index) => {
  const number = index + 1;
  const compactId = `R${String(number).padStart(2, "0")}`;
  return Object.freeze({
    ...round,
    number,
    id: `R-${String(number).padStart(3, "0")}`,
    compactId,
    findingId: `F-${String(number).padStart(3, "0")}`,
    evidenceId: `PBC-${String(number).padStart(3, "0")}`,
  });
}));

function plannedDate(index) {
  const day = 25 + Math.floor(index / 7);
  return `${day} أغسطس 2026`;
}

export function createAuditRounds() {
  return auditRoundBlueprints.map((round, index) => ({
    id: round.id,
    referenceId: round.compactId,
    title: round.title,
    status: index < 18 ? "complete" : index === 18 ? "active" : "planned",
    progress: index < 18 ? 100 : index === 18 ? 68 : 0,
    findings: 1,
    findingIds: [round.findingId],
    evidenceIds: [round.evidenceId],
    owner: round.owner,
    date: plannedDate(index),
    risk: round.risk,
    threshold: round.threshold,
    standards: [...round.standards],
    categoryKeys: [...round.categoryKeys],
    summary: round.findingSummary,
    action: round.action,
    documents: [
      { id: `${round.compactId}-WP`, name: `${round.compactId}-ورقة-عمل-${round.shortLabel}.xlsx`, type: "workpaper", status: "reviewed", metadataOnly: true },
      { id: `${round.compactId}-EV`, name: `${round.compactId}-دليل-مؤيد.pdf`, type: "evidence", status: "reviewed", metadataOnly: true },
    ],
  }));
}

export function createRoundEvidence() {
  return auditRoundBlueprints.map((round, index) => {
    const hashInput = `KOSIF-DEMO-5000-v7:${round.evidenceId}:v1`;
    return ({
    id: round.evidenceId,
    title: `حزمة أدلة — ${round.title}`,
    area: areaProfiles[round.categoryKeys[0]]?.label || round.title,
    categoryKeys: [...round.categoryKeys],
    due: plannedDate(index),
    status: index < 18 ? "approved" : index === 18 ? "review" : "pending",
    owner: round.owner,
    priority: round.risk,
    roundId: round.id,
    assertions: [...round.assertions],
    standardIds: [...round.standards],
    findingIds: [round.findingId],
    version: 1,
    fileName: `${round.compactId}-دليل-مؤيد.pdf`,
    hashAlgorithm: "sha256",
    hash: sha256HexSync(hashInput),
    hashInput,
  });
  });
}

export function createRoundFindings() {
  return auditRoundBlueprints.map((round, index) => ({
    id: round.findingId,
    title: round.findingTitle,
    area: areaProfiles[round.categoryKeys[0]]?.label || round.title,
    categoryKeys: [...round.categoryKeys],
    severity: round.risk,
    standard: round.standards[0],
    standardIds: [...round.standards],
    status: index < 18 ? "closed" : index === 18 ? "review" : "open",
    roundId: round.id,
    evidenceIds: [round.evidenceId],
    quantifiedAmount: Number.isFinite(round.quantifiedAmount) ? round.quantifiedAmount : null,
    quantifiedAmountMinor: Number.isFinite(round.quantifiedAmount)
      ? String(Math.round(round.quantifiedAmount * 100))
      : null,
    quantifiedBasis: round.quantifiedBasis || null,
    summary: round.findingSummary,
    recommendation: round.action,
  }));
}
